const labels: Record<string, string> = {
    clienteId: "Cliente (ID)",
    armazemId: "Armazém (ID)",
    produtoId: "Produto / SKU (ID)",
    pedidoId: "Pedido (ID)",
    pedidoEntradaId: "Pedido de entrada (ID)",
    pedidoSaidaId: "Pedido de saída (ID)",
    entradaId: "Entrada conferida (ID)",
    unidadeId: "Unidade logística (ID)",
    embalagemId: "Embalagem / DUN (ID)",
    enderecoId: "Endereço (ID)",
    conjuntoId: "Conjunto de posições (ID)",
    reservaId: "Reserva (ID)",
    notaOrigemId: "Nota de origem (ID)",
    itemNotaId: "Item da nota (ID)",
    baixaId: "Baixa física (ID)",
    servicoId: "Serviço (ID)",
    id: "Identificador",
    codigo: "Código",
    codigoUnidade: "UUID da unidade",
    codigoLido: "Código lido",
    versao: "Revisão atual",
    versaoUnidade: "Revisão atual da unidade",
    revisaoConteudo: "Revisão do conteúdo da etiqueta",
    operacaoId: "Identificador desta operação",
    quantidadePrevista: "Quantidade prevista",
    quantidadeBoa: "Quantidade boa recebida",
    quantidadeAvariada: "Quantidade avariada",
    chegouEm: "Chegada física real (ISO com fuso)",
    dataFifo: "Data FIFO",
    inicioArmazenagemEm: "Início da cobrança de armazenagem",
    retiradaEm: "Retirada física confirmada em",
    fisicoTotal: "Saldo físico total",
    disponivel: "Disponível para saída",
    reservado: "Reservado",
    emQuarentena: "Em quarentena",
    avariado: "Avariado",
    resolverPendentes: "Resolver pendências (Gestor)",
    referencia: "Referência",
    motivo: "Motivo / justificativa",
    documentoFiscal: "CPF / CNPJ",
    codigoDun: "DUN da embalagem",
    quantidadeProduto: "Quantidade de produto por embalagem",
    precisaoQuantidade: "Casas decimais da quantidade",
    antecedenciaAvisoDias: "Antecedência do aviso (dias)",
    pagina: "Página (início 0)",
    tamanho: "Itens por página (1–100)",
    valor: "Incluir valor (Supervisor / Gestor)",
    fuso: "Fuso do relatório",
    xml: "XML existente da NF-e",
    xmls: "XMLs comprovantes da retirada",
    protocolo: "Protocolo existente NOTAZZ",
    coberturas: "Cobertura por reserva / nota / SKU",
    remanescentes: "Destinos dos remanescentes",
    destinos: "Posições de destino",
    itens: "Itens",
    notas: "Notas de mercadoria",
    medidas: "Medidas físicas",
    prova: "Prova da operação original",
    resolucao: "Resolução financeira histórica (Gestor)",
    conteudoHash: "SHA-256 do conteúdo",
    ocorridaEm: "Instante real do fato (ISO com fuso)",
    identidadeFato: "Identidade do registro de contingência",
    efeitoRegistradoNoWms: "Efeito já registrado no WMS",
    dependencias: "Identidades das dependências",
    dados: "Dados do fato de contingência",
    situacao: "Situação informada",
    origem: "Origem",
    natureza: "Natureza",
    periodoInicio: "Início do período",
    periodoFim: "Fim exclusivo do período",
    valorMercadoria: "Valor da mercadoria da nota",
    totalItens: "Total de registros",
    totalPaginas: "Total de páginas",
};
export const label = (key: string) =>
    labels[key] ??
    key
        .replace(/([a-z])([A-Z])/g, "$1 $2")
        .replace(/^./, (s) => s.toUpperCase());
export const display = (v: unknown): string =>
    v === null || v === undefined
        ? "Não informado"
        : typeof v === "boolean"
          ? v
              ? "Sim"
              : "Não"
          : String(v);
