import tools.jackson.databind.JsonNode;
import java.time.Instant;
import java.util.*;

/** Doc22 limites compostos e doc24 integralidade multiSKU, em familia nova sem gate SQL. */
final class CapacidadeIntegralD29 {
 final EnsaioD29 x;final JornadasD29 j;final PendenciasD29 p;
 CapacidadeIntegralD29(EnsaioD29 x){this.x=x;j=new JornadasD29(x);p=new PendenciasD29(x);}
 static Map<String,Object> m(Object...v){return EnsaioD29.m(v);}
 JsonNode post(String n,String r,Object d,String role,int status)throws Exception{return x.call(n,"POST",r,d,role,status);}
 JsonNode get(String n,String r)throws Exception{return x.call(n,"GET",r,null,"OPERACAO",200);}
 Map<String,Object> limits(int weight,int height,int width,int depth,int stack){return m("pesoKg",weight,"alturaMetros",height,"larguraMetros",width,"profundidadeMetros",depth,"empilhamentoMaximo",stack);}
 JsonNode config(JsonNode a,String type,Map<String,Object> l,String role,int status)throws Exception{return x.call("D29 configurar perfil "+type+" "+a.path("codigo").asString(),"PUT","/api/v1/enderecos/"+a.path("id").asLong()+"/capacidade",m("versao",a.path("versao").asLong(),"tipoUnidadePermitido",type,"limites",l,"motivo",x.round+" limites ficticios"),role,status);}
 JsonNode unit(String ref)throws Exception{long pe=j.entry(ref,10);j.arrival(pe,10,Instant.now());post("D29 efetivar10 "+ref,j.pe(pe)+"/efetivacao",m("versao",j.pv(pe),"aceitarDivergencias",false,"motivo",x.round+" recebimento10 ficticio"),"SUPERVISOR",200);long en=j.get(j.pe(pe)+"/entradas").path("itens").get(0).path("id").asLong();return j.unitize(pe,en,10);}
 Map<String,Object> movement(JsonNode u,List<JsonNode> a,Long group,int weight,int height,int width,int depth,int stack){var d=x.command();d.put("versaoUnidade",u.path("versao").asLong());d.put("destinos",a.stream().map(e->m("enderecoId",e.path("id").asLong(),"codigoLido",e.path("codigo").asString())).toList());if(group!=null)d.put("conjuntoId",group);d.put("medidas",m("pesoKg",weight,"alturaMetros",height,"larguraMetros",width,"profundidadeMetros",depth,"empilhamento",stack,"posicoesNecessarias",a.size()));return d;}
 void invalidMove(String n,JsonNode u,Map<String,Object> d)throws Exception{var before=get(n+" antes",j.unit(u)+"/estoque");post(n,j.unit(u)+"/movimentos",d,"OPERACAO",409);var after=get(n+" depois",j.unit(u)+"/estoque");x.assertion(n+" sem medida/ocupacao/movimento parcial",before.equals(after),before,after);}
 void run()throws Exception {
  if(x.ids.containsKey("retomadaDe"))throw new IllegalStateException("D29_CAPACIDADE_NOVA_FAMILIA_EXIGIDA");x.ids.put("oraculosSQL",m("fontes",List.of("docs/22-enderecamento-movimentacao-e-estoque.md:23-33","docs/24-pedido-saida-fifo-e-reserva.md:23,68","D29-VIG-P09","D29-L-P03","D29-L-P05"),"capacidade","Peso1000/dimensoes2/stack2 exatos permitidos; 1001/cada3 recusados409 sem medidas/ocupacao/movimento. TipoBOBINA/PALLET recusado. Duasposicoes500+500kg/larguras2+2; altura/profundidade/stack min1, teto1000/4/1/1/1; grupos acima400, movimentos acima409; positivo exato ocupa2.","multiSKU","Duas unidades10 de SKUs distintos, ordem8+8 criada quando ambaslivres. CompetidorSKU2reserva8; multi8+8recusa409 sem prefixoSKU1; reversaoexplicita competidor; multi8+8 confirma2reservas, fis20/res16/bloq4/disp0. Sugestao nao reserva e cada recusa preserva snapshot.","limite","Sem geometricafisica/SQLlocks nativos; recusa precondicao nao e faultSQL tardio."));x.save();j.cadastros();var firstProduct=x.product;var firstPack=x.pack;var u=unit("CAPSKU1");var max=j.address("MAX","ARMAZENAGEM");
  config(max,"PALLET",limits(1000,2,2,2,2),"OPERACAO",403);
  int[][] bad={{1001,2,2,2,2},{1000,3,2,2,2},{1000,2,3,2,2},{1000,2,2,3,2},{1000,2,2,2,3}};
  String[] fields={"peso","altura","largura","profundidade","empilhamento"};for(int i=0;i<bad.length;i++){int[] b=bad[i];invalidMove("D29 limite individual "+fields[i]+" acima",u,movement(u,List.of(max),null,b[0],b[1],b[2],b[3],b[4]));}
  var wrong=j.address("BOB","ARMAZENAGEM");wrong=config(wrong,"BOBINA",limits(1000,2,2,2,2),"GESTOR",200);invalidMove("D29 tipoPALLET destinoBOBINA",u,movement(u,List.of(wrong),null,1000,2,2,2,2));
  post("D29 todos cinco limites exatos positivos",j.unit(u)+"/movimentos",movement(u,List.of(max),null,1000,2,2,2,2),"OPERACAO",200);u=j.actual(u);var stock=get("D29 umaocupacao medidasexatas",j.unit(u)+"/estoque");x.assertion("D29 maximo nao e acima",stock.path("posicoes").size()==1,1,stock);var beforeAddress=get("D29 enderecoocupado antesconfig","/api/v1/enderecos/"+max.path("id").asLong());config(beforeAddress,"PALLET",limits(1001,2,2,2,2),"GESTOR",409);x.assertion("D29 configuracaoocupado conserva perfil",beforeAddress.equals(get("D29 enderecoocupado aposrecusa","/api/v1/enderecos/"+max.path("id").asLong())),beforeAddress,"semalterar");x.ids.put("unidadeCapacidade1",u);x.save();
  x.product=post("D29 segundoSKU mesmo propietario","/api/v1/produtos",m("clienteId",x.clientId,"sku",x.round+"SKU2","descricao",x.round+" SKU2 ficticio","unidadeMedida","UN","tipoQuantidade","CONTAGEM","precisaoQuantidade",0,"controlaLote",false,"controlaValidade",false),"GESTOR",201);x.pack=post("D29 segundoDUN","/api/v1/embalagens",m("produtoId",x.product.path("id").asLong(),"codigoDun",x.round+"DUN2","descricao",x.round+" DUN2","quantidadeProduto",10),"GESTOR",201);var secondProduct=x.product;var v=unit("CAPSKU2");var a=j.address("C1","ARMAZENAGEM");var b=j.address("C2","ARMAZENAGEM");a=config(a,"PALLET",limits(500,1,2,1,1),"GESTOR",200);b=config(b,"PALLET",limits(500,2,2,2,2),"GESTOR",200);
  var valid=limits(1000,1,4,1,1);int[][] invalidGroups={{1001,1,4,1,1},{1000,2,4,1,1},{1000,1,5,1,1},{1000,1,4,2,1},{1000,1,4,1,2}};
  for(int i=0;i<invalidGroups.length;i++){int[] t=invalidGroups[i];post("D29 teto conjunto "+fields[i]+" recusa","/api/v1/conjuntos-posicoes",m("armazemId",x.warehouseId,"codigo",x.round+"GINV"+i,"enderecoAId",a.path("id").asLong(),"enderecoBId",b.path("id").asLong(),"limites",limits(t[0],t[1],t[2],t[3],t[4]),"motivo",x.round+" teto composto violado"),"GESTOR",400);}
  var group=post("D29 conjunto teto exato composto","/api/v1/conjuntos-posicoes",m("armazemId",x.warehouseId,"codigo",x.round+"GOK","enderecoAId",a.path("id").asLong(),"enderecoBId",b.path("id").asLong(),"limites",valid,"motivo",x.round+" conjunto ficticio composto"),"GESTOR",201);
  for(int i=0;i<invalidGroups.length;i++){int[] t=invalidGroups[i];invalidMove("D29 medida acima conjunto "+fields[i],v,movement(v,List.of(a,b),group.path("id").asLong(),t[0],t[1],t[2],t[3],t[4]));}
  post("D29 medida conjunta exata ocupa ambas",j.unit(v)+"/movimentos",movement(v,List.of(a,b),group.path("id").asLong(),1000,1,4,1,1),"OPERACAO",200);v=j.actual(v);x.assertion("D29 composto ocupa2 sem prefixo",get("D29 composto GETduas",j.unit(v)+"/estoque").path("posicoes").size()==2,2,"ocupacao2");x.ids.put("unidadeCapacidade2",v);x.ids.put("produto2",secondProduct);x.ids.put("conjuntoCapacidade",group);x.save();
  x.product=firstProduct;x.pack=firstPack;multi(firstProduct,secondProduct);x.save();
 }
 void multi(JsonNode first,JsonNode second)throws Exception {
  x.precheck("reserva-multiSKU-integral",false);var d=x.command();d.putAll(m("clienteId",x.clientId,"armazemId",x.warehouseId,"referencia",x.round+"MULTI","itens",List.of(m("produtoId",first.path("id").asLong(),"quantidade",8),m("produtoId",second.path("id").asLong(),"quantidade",8))));var order=post("D29 pedido integral8+8","/api/v1/pedidos-saida",d,"OPERACAO",201).path("pedido");d=x.command();d.putAll(m("clienteId",x.clientId,"armazemId",x.warehouseId,"referencia",x.round+"COMP2","itens",List.of(m("produtoId",second.path("id").asLong(),"quantidade",8))));var competitor=post("D29 competidor somenteSKU2","/api/v1/pedidos-saida",d,"OPERACAO",201).path("pedido");competitor=post("D29 competidor reservaSKU2 oito",j.ps(competitor)+"/reserva",x.version(competitor),"OPERACAO",200).path("pedido");var balance1=j.balance();var before=j.get(j.ps(order));p.code("D29 multiitem ultimoSKU indisponivel",post("D29 multi8+8 semprefixoSKU1",j.ps(order)+"/reserva",x.version(order),"OPERACAO",409),"SALDO_INSUFICIENTE");x.assertion("D29 multi recusa ultimo preservaSKU1/pedido",before.equals(j.get(j.ps(order)))&&balance1.equals(j.balance())&&before.path("reservas").isEmpty(),"SKU1livre10/pedidoRASCUNHO/reservas0",m("pedido",j.get(j.ps(order)),"saldo1",j.balance()));post("D29 reversao explicita competidorSKU2",j.ps(competitor)+"/reversao-reserva",x.version(competitor),"SUPERVISOR",200);var reserved=post("D29 multiitem integral dois8",j.ps(order)+"/reserva",x.version(order),"OPERACAO",200);x.assertion("D29 duasreservas integrais8+8",reserved.path("pedido").path("reservas").size()==2&&reserved.path("pedido").path("reservas").get(0).path("quantidade").decimalValue().intValueExact()==8&&reserved.path("pedido").path("reservas").get(1).path("quantidade").decimalValue().intValueExact()==8,"2x8",reserved);for(var product:List.of(first,second)){var b=get("D29 saldo final porSKU "+product.path("id").asLong(),"/api/v1/estoque/saldo?clienteId="+x.clientId+"&armazemId="+x.warehouseId+"&produtoId="+product.path("id").asLong());x.assertion("D29 saldo porSKU10/8/2/0",b.path("fisicoTotal").decimalValue().intValueExact()==10&&b.path("reservado").decimalValue().intValueExact()==8&&b.path("bloqueado").decimalValue().intValueExact()==2&&b.path("disponivel").decimalValue().signum()==0,"10/8/2/0",b);}x.ids.put("pedidoMulti8",reserved);x.ids.put("pedidoCompetidorSKU2",competitor);x.save();
 }
}
