import tools.jackson.databind.JsonNode;
import java.time.*;
import java.util.*;

final class CargaContagemD29 {
 final EnsaioD29 x;final JornadasD29 j;final PendenciasD29 p;
 CargaContagemD29(EnsaioD29 x){this.x=x;j=new JornadasD29(x);p=new PendenciasD29(x);}
 static Map<String,Object>m(Object...v){return EnsaioD29.m(v);}
 JsonNode post(String n,String r,Object b,String role,int e)throws Exception{return x.call(n,"POST",r,b,role,e);}
 void run()throws Exception{
  if(x.ids.containsKey("retomadaDe")){x.product=x.call("D29 carga retoma GET produto","GET","/api/v1/produtos/"+x.ids.get("produtoId"),null,"GESTOR",200);x.pack=x.call("D29 carga retoma GET embalagem","GET","/api/v1/embalagens/"+x.ids.get("embalagemId"),null,"GESTOR",200);new RegressaoD29(x).cargas();return;}
  x.ids.put("oraculosSQL",m("contagem","100fisico/reserva80/contado70: aplica409 mantém100/80; reversãoexpressa e novaleiturarastreavel70: delta-30, saldo70,reserva0; novoajuste0 liberaocupação e conservaorigens/históricos","carga","carga20 revisao inicial+nova revisão preparacao+confirmacao etiquetas adiciona20uma vez; cancelamento3semfisico; nao inferir estoqueXML","limite","recusa precondicao nao e fault SQL meio transação"));x.save();j.cadastros();x.precheck("contagem-fixture",false);
  long pe=j.entry("CONT100",100);j.arrival(pe,100,Instant.now());post("D29 contagem efetivar100",j.pe(pe)+"/efetivacao",m("versao",j.pv(pe),"aceitarDivergencias",false,"motivo",x.round+" fisicoconferido100"),"SUPERVISOR",200);long en=j.get(j.pe(pe)+"/entradas").path("itens").get(0).path("id").asLong();var u=j.unitize(pe,en,100);var address=j.address("CONT","ARMAZENAGEM");post("D29 contagemenderecar",j.unit(u)+"/movimentos",j.move(u,address),"OPERACAO",200);u=j.actual(u);x.ids.put("pedidoEntradaId",pe);x.ids.put("unidades",List.of(u));
  var order=j.order("RES80",80);var reserved=post("D29 contagemreserva80",j.ps(order)+"/reserva",x.version(order),"OPERACAO",200).path("pedido");u=j.actual(u);var body=p.reading(u,70);var count=post("D29 contagem70aindareserva80","/api/v1/contagens",body,"OPERACAO",200);x.ids.put("contagemReservaId",count.path("id").asLong());x.ids.put("pedidoReservaContagemId",order.path("id").asLong());x.save();var cmd=p.application(count,u);var no=post("D29 contagem70recusaantesliberacao","/api/v1/contagens/"+count.path("id").asLong()+"/aplicar",cmd,"SUPERVISOR",409);x.assertion("D29 recusareserva mantem10080",no.path("codigo").asString().equals("PENDENTE_RESERVA")&&j.balance().path("fisicoTotal").decimalValue().intValueExact()==100&&j.balance().path("reservado").decimalValue().intValueExact()==80,"PENDENTE_RESERVA/fisico100/reserva80",m("recusa",no,"saldo",j.balance()));
  post("D29 contagemreversaociente",j.ps(reserved)+"/reversao-reserva",x.version(reserved),"SUPERVISOR",200);u=j.actual(u);count=post("D29 novaobservacao70aposreversao","/api/v1/contagens",p.reading(u,70),"OPERACAO",200);cmd=p.application(count,u);var applied=post("D29 aplicar70delta30","/api/v1/contagens/"+count.path("id").asLong()+"/aplicar",cmd,"SUPERVISOR",200);x.assertion("D29 ajuste70replaysemduplo30",applied.equals(post("D29 replayajuste70","/api/v1/contagens/"+count.path("id").asLong()+"/aplicar",cmd,"SUPERVISOR",200))&&j.balance().path("fisicoTotal").decimalValue().intValueExact()==70&&j.balance().path("reservado").decimalValue().signum()==0,"70/0/replayunico",m("aplicado",applied,"saldo",j.balance()));x.ids.put("contagem70",applied);x.save();
  x.precheck("contagem-zero",false);u=j.actual(u);count=post("D29 contagemzerocomprovada","/api/v1/contagens",p.reading(u,0),"OPERACAO",200);cmd=p.application(count,u);applied=post("D29 ajustarzero","/api/v1/contagens/"+count.path("id").asLong()+"/aplicar",cmd,"SUPERVISOR",200);x.assertion("D29 zeroencerraIDeliberaocupacaonaohistoria",!j.actual(u).path("ativa").asBoolean()&&j.get(j.unit(u)+"/estoque").path("posicoes").isEmpty()&&j.balance().path("fisicoTotal").decimalValue().signum()==0,"0/inativo/posicoes0",applied);x.ids.put("contagemZero",applied);x.save();
  new RegressaoD29(x).cargas();
 }
}
