import tools.jackson.databind.JsonNode;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import java.net.http.*;
import java.net.*;

/** Barreira apenas no cliente HTTP. Nenhuma conexao/porteira SQL nesta classe. */
final class ConcorrenciaD29 {
 final EnsaioD29 x;final JornadasD29 j;
 ConcorrenciaD29(EnsaioD29 x){this.x=x;j=new JornadasD29(x);}
 static Map<String,Object> m(Object...v){return EnsaioD29.m(v);}
 final List<Map<String,Object>> pairs=new ArrayList<>();final List<Long> orders=new ArrayList<>();
 void run()throws Exception{
  x.ids.put("oraculosSQL",m("repeticoes",3,"porPar","estoque novo100, dois pedidos80; 1RESERVADO80/1RASCUNHOsemreservas; fisico100porpar, bloqueado20porpar; perdedorsemoperacaoconfirmada/auditoriareserva; replaywinner mesmaUUIDsemduplicar","controle","duasHTTPmesmaUUIDwinner retornam200/200snapshotoriginal; nao e nova mutacao","metodo","barreiraHTTP/timing/resultado/SELECT posterior; nao provarlocks nativos nem duas sessoes SQL"));x.ids.put("nativeLocksComprovados",false);x.save();j.cadastros();
  for(int rep=1;rep<=3;rep++){
   x.precheck("concorrencia-par"+rep,false);long pe=j.entry("CON"+rep,100);j.arrival(pe,100,Instant.now());
   x.call("D29 conc efetivar100 par"+rep,"POST",j.pe(pe)+"/efetivacao",m("versao",j.pv(pe),"aceitarDivergencias",false,"motivo",x.round+" estoque100par"+rep),"SUPERVISOR",200);
   long en=j.get(j.pe(pe)+"/entradas").path("itens").get(0).path("id").asLong();var unit=j.unitize(pe,en,100);var address=j.address("CON"+rep,"ARMAZENAGEM");x.call("D29 conc enderecar100","POST",j.unit(unit)+"/movimentos",j.move(unit,address),"OPERACAO",200);
   var a=j.order("A"+rep,80);var b=j.order("B"+rep,80);orders.add(a.path("id").asLong());orders.add(b.path("id").asLong());x.ids.put("concorrenciaPedidos",orders);x.save();var da=x.version(a);var db=x.version(b);
   boolean inverted=rep==2;var responses=pair("PAR"+rep,List.of(j.ps(inverted?b:a)+"/reserva",j.ps(inverted?a:b)+"/reserva"),inverted?List.of(db,da):List.of(da,db),true);
   var winners=responses.stream().filter(r->r.path("pedido").path("id").asLong()>0).toList();if(winners.size()!=1)throw new IllegalStateException("D29_VENCEDOR_RESPOSTA_NAO_UNICO");var winningResponse=winners.get(0);long winningId=winningResponse.path("pedido").path("id").asLong();if(winningId!=a.path("id").asLong()&&winningId!=b.path("id").asLong())throw new IllegalStateException("D29_VENCEDOR_ID_FORA_PAR");var winner=winningId==a.path("id").asLong()?a:b;var loser=winningId==a.path("id").asLong()?b:a;var cmd=winningId==a.path("id").asLong()?da:db;x.ids.put("ordemSubmissaoPar"+rep,inverted?List.of(b.path("id").asLong(),a.path("id").asLong()):List.of(a.path("id").asLong(),b.path("id").asLong()));
   var live=j.get(j.ps(winner));var loss=j.get(j.ps(loser));x.assertion("D29 conc par"+rep+" umreservado outrosemefeitos",live.path("situacao").asString().equals("RESERVADO")&&live.path("reservas").size()==1&&live.path("reservas").get(0).path("quantidade").decimalValue().intValueExact()==80&&loss.path("situacao").asString().equals("RASCUNHO")&&loss.path("reservas").isEmpty(),"RESERVADO80/RASCUNHO0",m("winner",live,"loser",loss));
   var balance=j.balance();x.assertion("D29 conc saldo cumulativo par"+rep,balance.path("fisicoTotal").decimalValue().intValueExact()==100*rep&&balance.path("reservado").decimalValue().intValueExact()==80*rep&&balance.path("bloqueado").decimalValue().intValueExact()==20*rep&&balance.path("disponivel").decimalValue().signum()==0,"fisico="+100*rep+"/reserva="+80*rep+"/bloqueado="+20*rep+"/disponivel0",balance);
   var replay=pair("REPLAY"+rep,List.of(j.ps(winner)+"/reserva",j.ps(winner)+"/reserva"),List.of(cmd,cmd),false);x.assertion("D29 conc controle200200snapshot unico par"+rep,replay.get(0).equals(winningResponse)&&replay.get(1).equals(winningResponse)&&j.balance().equals(balance),winningResponse,replay);j.get(j.ps(winner));j.get(j.ps(loser));
  }
  sequential();
  x.ids.put("concorrenciaPares",pairs);x.save();
 }
 void sequential()throws Exception{
  x.precheck("concorrencia-controle-sequencial",false);long pe=j.entry("SEQ",100);j.arrival(pe,100,Instant.now());x.call("D29 sequencial efetivar100","POST",j.pe(pe)+"/efetivacao",m("versao",j.pv(pe),"aceitarDivergencias",false,"motivo",x.round+" controle100"),"SUPERVISOR",200);long en=j.get(j.pe(pe)+"/entradas").path("itens").get(0).path("id").asLong();var u=j.unitize(pe,en,100);var addr=j.address("SEQ","ARMAZENAGEM");x.call("D29 sequencial enderecar","POST",j.unit(u)+"/movimentos",j.move(u,addr),"OPERACAO",200);var a=j.order("SEQ-A",80);var b=j.order("SEQ-B",80);orders.add(a.path("id").asLong());orders.add(b.path("id").asLong());x.ids.put("concorrenciaPedidos",orders);String beginA=Instant.now().toString();var ok=x.call("D29 sequencial A200","POST",j.ps(a)+"/reserva",x.version(a),"OPERACAO",200);String endA=Instant.now().toString();String beginB=Instant.now().toString();var no=x.call("D29 sequencial B409","POST",j.ps(b)+"/reserva",x.version(b),"OPERACAO",409);String endB=Instant.now().toString();var loss=j.get(j.ps(b));x.assertion("D29 controle sequencial um80 outro0",ok.path("pedido").path("id").equals(a.path("id"))&&loss.path("reservas").isEmpty()&&loss.path("situacao").asString().equals("RASCUNHO"),"A80/B0",m("A",ok,"B",no,"GETB",loss));var bal=j.balance();x.assertion("D29 controle saldo final40032080",bal.path("fisicoTotal").decimalValue().intValueExact()==400&&bal.path("reservado").decimalValue().intValueExact()==320&&bal.path("bloqueado").decimalValue().intValueExact()==80&&bal.path("disponivel").decimalValue().signum()==0,"400/320/80/0",bal);x.ids.put("controleSequencial",m("pedidos",List.of(a.path("id").asLong(),b.path("id").asLong()),"inicioA",beginA,"fimA",endA,"inicioB",beginB,"fimB",endB,"semSobreposicao",!Instant.parse(beginB).isBefore(Instant.parse(endA))));j.get(j.ps(a));x.save();
 }
 List<JsonNode> pair(String name,List<String>routes,List<Map<String,Object>>bodies,boolean competition)throws Exception{
  var ready=new CountDownLatch(2);var start=new CountDownLatch(1);var timings=Collections.synchronizedList(new ArrayList<Map<String,Object>>());String jwt=x.token("OPERACAO",Map.of());
  try(var pool=Executors.newFixedThreadPool(2)){
   var fs=new ArrayList<Future<JsonNode>>();
   for(int index=0;index<2;index++){final int i=index;fs.add(pool.submit(()->{Thread.currentThread().setName("D29-HTTP-"+name+"-"+i);ready.countDown();if(!start.await(15,TimeUnit.SECONDS))throw new IllegalStateException("D29_BARREIRA_TIMEOUT");long begin=System.nanoTime();String time=Instant.now().toString();var req=HttpRequest.newBuilder(URI.create(x.base+routes.get(i))).timeout(Duration.ofSeconds(45)).header("Authorization","Bearer "+jwt).header("X-Request-Id",x.round+"-"+UUID.randomUUID()).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(x.json.writeValueAsString(bodies.get(i)))).build();var response=x.http.send(req,HttpResponse.BodyHandlers.ofString());long end=System.nanoTime();timings.add(m("indice",i,"inicioUtc",time,"fimUtc",Instant.now().toString(),"inicioNano",begin,"fimNano",end,"duracaoMs",(end-begin)/1_000_000.0,"status",response.statusCode(),"RequestId",response.headers().firstValue("X-Request-Id").orElse(null)));synchronized(x){return x.recordResponse("D29 concorrencia "+name+" indice"+i,"POST",routes.get(i),bodies.get(i),"OPERACAO",200,response,competition);}}));}
   if(!ready.await(15,TimeUnit.SECONDS))throw new IllegalStateException("D29_CLIENTES_NAO_PRONTOS");String release=Instant.now().toString();start.countDown();var jvm=sampleJVM(name);var results=List.of(fs.get(0).get(60,TimeUnit.SECONDS),fs.get(1).get(60,TimeUnit.SECONDS));var statuses=timings.stream().map(t->((Number)t.get("status")).intValue()).sorted().toList();x.assertion("D29 parHTTP "+name+" conjunto esperado",statuses.equals(competition?List.of(200,409):List.of(200,200)),competition?List.of(200,409):List.of(200,200),timings);var sorted=timings.stream().sorted(Comparator.comparingLong(t->((Number)t.get("inicioNano")).longValue())).toList();boolean overlap=((Number)sorted.get(1).get("inicioNano")).longValue()<((Number)sorted.get(0).get("fimNano")).longValue();pairs.add(m("par",name,"barreiraLiberadaUtc",release,"clientesProntos",2,"tempos",new ArrayList<>(timings),"intervalosHTTPsobrepostos",overlap,"jvm",jvm,"naoProvaSQLNativo",true));x.ids.put("concorrenciaPares",pairs);x.save();return results;
  }finally{start.countDown();}
 }
 Map<String,Object> sampleJVM(String name){
  String begin=Instant.now().toString();try{
   var pb=new ProcessBuilder(java.nio.file.Path.of(System.getProperty("java.home"),"bin","jcmd.exe").toString(),Long.toString(x.app.pid()),"Thread.print","-l");pb.environment().clear();String sr=System.getenv("SystemRoot");if(sr!=null)pb.environment().put("SystemRoot",sr);var p=pb.start();String snapshot=EnsaioD29.processOutputLimited(p,8000);if(!x.secret.isEmpty())snapshot=snapshot.replace(x.secret,"[SEGREDO_OMITIDO]");var file=x.evidence.resolve("d29-"+x.round+"-jvm-"+name+".txt");java.nio.file.Files.writeString(file,snapshot);return m("arquivo",file.getFileName().toString(),"pidProprio",x.app.pid(),"inicioUtc",begin,"fimUtc",Instant.now().toString(),"capturado",true,"limite","Snapshot JVM amostrado apos barreira; nao certifica 2sessoesSQL/locks nem permanencia simultanea no servidor");
  }catch(Exception e){return m("capturado",false,"classeErro",e.getClass().getSimpleName(),"inicioUtc",begin,"limite","Timing HTTP/resultados/SELECT posterior continuam distintos de prova SQL nativa");}
 }
}
