import tools.jackson.databind.JsonNode;
import java.util.*;
import java.time.*;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.net.*;
import java.net.http.*;
import java.security.MessageDigest;

/** Excel e contingencia locais reais sobre familia ficticia nova; sem emissor/dispositivo. */
final class ConformidadeD29 {
 final EnsaioD29 x;final JornadasD29 j;final PendenciasD29 p;
 ConformidadeD29(EnsaioD29 x){this.x=x;j=new JornadasD29(x);p=new PendenciasD29(x);}
 static Map<String,Object>m(Object...v){return EnsaioD29.m(v);}
 JsonNode get(String r)throws Exception{return x.call("D29 conformidade GET "+r,"GET",r,null,"GESTOR",200);}
 JsonNode post(String n,String r,Object b,String role,int e)throws Exception{return x.call(n,"POST",r,b,role,e);}
 void run()throws Exception {
  if(x.ids.containsKey("retomadaDe")){resume();closing();return;}
  x.ids.put("oraculosSQL",m("XLSX","Previa nao cadastra; texto01 e numero2format00 preservam01/02; 1.5format00 nao arredonda; formula recusada; hash divergente409; conflito cadastral aposprevia409sem lote parcial; replay nao duplica.","contingencia","L2 registrada antesL1: dependencia ausente409/semcontagem; aposL1 conciliada L2executa uma vez; alvo somenteDTOaninhado; identidade global comconteudoalterado409; Operacao semconciliacao403; fisico10mantido.","encerramento","Cliente comsaldo identificado: solicitarENCERRAMENTO_PENDENTE permitido, inativacao409conservaestoque.","limites","Conflito XLSX anterior aos INSERTs nao fault SQL tardio; sem coleta fisica/device ou documentos externos."));x.save();j.cadastros();excel();contingency();closing();
 }
 byte[] sheet(String suffix,String type)throws Exception {
  try(var w=new org.apache.poi.xssf.usermodel.XSSFWorkbook();var out=new java.io.ByteArrayOutputStream()){
   var s=w.createSheet("Enderecos");String[]header={"codigo","rua","nivel","posicao","descricao","tipo","sequenciaColeta"};var h=s.createRow(0);for(int c=0;c<header.length;c++)h.createCell(c).setCellValue(header[c]);
   for(int n=1;n<=2;n++){var row=s.createRow(n);String[]v={x.round+suffix+n,x.round+suffix,"0",n==1?"01":"02",x.round+" Excel ficticio","ARMAZENAGEM",Integer.toString(500+n)};for(int c=0;c<v.length;c++)row.createCell(c).setCellValue(v[c]);if(n==2){var cell=row.getCell(3);cell.setCellValue(type.equals("FRACAO")?1.5:2);var style=w.createCellStyle();style.setDataFormat(w.createDataFormat().getFormat("00"));cell.setCellStyle(style);if(type.equals("FORMULA"))cell.setCellFormula("1+1");}}
   w.write(out);return out.toByteArray();
  }
 }
 JsonNode preview(String suffix,String type)throws Exception {
  byte[]sheet=sheet(suffix,type);String sha=HexFormat.of().withUpperCase().formatHex(MessageDigest.getInstance("SHA-256").digest(sheet));String file="d29-"+x.round+"-excel-"+suffix+".xlsx";Files.write(x.evidence.resolve(file),sheet);String boundary="D29"+UUID.randomUUID().toString().replace("-","");var out=new java.io.ByteArrayOutputStream();
  out.write(("--"+boundary+"\r\nContent-Disposition: form-data; name=\"comando\"\r\nContent-Type: application/json\r\n\r\n"+x.json.writeValueAsString(x.command())+"\r\n--"+boundary+"\r\nContent-Disposition: form-data; name=\"arquivo\"; filename=\""+file+"\"\r\nContent-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet\r\n\r\n").getBytes(StandardCharsets.UTF_8));out.write(sheet);out.write(("\r\n--"+boundary+"--\r\n").getBytes(StandardCharsets.UTF_8));String route="/api/v1/armazens/"+x.warehouseId+"/importacoes-enderecos/previa";
  var request=HttpRequest.newBuilder(URI.create(x.base+route)).timeout(Duration.ofSeconds(40)).header("Authorization","Bearer "+x.token("GESTOR",Map.of())).header("X-Request-Id",x.round+"-"+UUID.randomUUID()).header("Content-Type","multipart/form-data; boundary="+boundary).POST(HttpRequest.BodyPublishers.ofByteArray(out.toByteArray())).build();var response=x.http.send(request,HttpResponse.BodyHandlers.ofString());var d=x.recordResponse("D29 XLSX previa "+type,"POST",route,m("arquivo",file,"sha256",sha,"linhas",2,"classe",type),"GESTOR",200,response,false);get("/api/v1/importacoes-enderecos/"+d.path("id").asLong());return d;
 }
 void excel()throws Exception {
  x.precheck("Excel-previa-confirmacao",false);String list="/api/v1/enderecos?armazemId="+x.warehouseId+"&tamanho=100";
  for(String type:List.of("FRACAO","FORMULA")){var d=preview(type,type);x.assertion("D29 XLSX nao arredonda nem executa "+type,!d.path("erros").isEmpty()&&get(list).path("totalItens").asLong()==0,"erro/cadastros0",d);var c=x.version(d);c.put("arquivoHash",d.path("arquivoHash").asString());var no=post("D29 XLSX com erros nao confirma "+type,"/api/v1/importacoes-enderecos/"+d.path("id").asLong()+"/confirmacao",c,"GESTOR",409);p.code("D29 XLSX com erros codigo",no,"PREVIA_INVALIDA");}
  var d=preview("OK","VALIDO");x.assertion("D29 XLSX identidades01/02 e previa semefeito",d.path("erros").isEmpty()&&d.path("linhas").get(0).path("endereco").path("posicao").asString().equals("01")&&d.path("linhas").get(1).path("endereco").path("posicao").asString().equals("02")&&get(list).path("totalItens").asLong()==0,"01/02/enderecos0",d);String route="/api/v1/importacoes-enderecos/"+d.path("id").asLong()+"/confirmacao";var c=x.version(d);c.put("arquivoHash","0".repeat(64));p.code("D29 XLSX hash divergente",post("D29 XLSX hash recusado",route,c,"GESTOR",409),"PREVIA_INVALIDA");c=x.version(d);c.put("arquivoHash",d.path("arquivoHash").asString());post("D29 XLSX Operacao nao confirma",route,c,"OPERACAO",403);var yes=post("D29 XLSX lote correto",route,c,"GESTOR",200);x.assertion("D29 XLSX replay 2enderecos",yes.equals(post("D29 XLSX replay",route,c,"GESTOR",200))&&get(list).path("totalItens").asLong()==2,"2enderecos/mesmosnapshot",yes);
  var late=preview("LATE","VALIDO");var conflict=x.json.convertValue(late.path("linhas").get(1).path("endereco"),Map.class);post("D29 XLSX conflito real posterior previa","/api/v1/enderecos",conflict,"GESTOR",201);c=x.version(late);c.put("arquivoHash",late.path("arquivoHash").asString());p.code("D29 XLSX revalida lote inteiro",post("D29 XLSX lote409aposconcorrente", "/api/v1/importacoes-enderecos/"+late.path("id").asLong()+"/confirmacao",c,"GESTOR",409),"LOTE_DIVERGENTE");x.assertion("D29 XLSX nenhum primeiro item parcial",get(list).path("totalItens").asLong()==3,"2anteriores+1conflito/primeiroLATEausente",get(list));x.ids.put("excelConfirmado",yes);x.save();
 }
 JsonNode receive(String suffix)throws Exception {
  long pe=j.entry(suffix,5);j.arrival(pe,5,Instant.now());post("D29 contingencia efetivar5 "+suffix,j.pe(pe)+"/efetivacao",m("versao",j.pv(pe),"aceitarDivergencias",false,"motivo",x.round+" conferencia5"),"SUPERVISOR",200);long id=j.get(j.pe(pe)+"/entradas").path("itens").get(0).path("id").asLong();return j.unitize(pe,id,5);
 }
 Map<String,Object> line(JsonNode u,String id,Instant at,List<String>deps) {
  var observation=p.reading(u,5);observation.put("observadoEm",at.toString());var d=x.command();d.putAll(m("identidadeFato",id,"clienteId",x.clientId,"armazemId",x.warehouseId,"tipo","CONTAGEM","ocorridaEm",at.toString(),"operador",x.round+" ficticio","fonte",x.round+" observacao ficticia atual5","efeitoRegistradoNoWms",false,"dependencias",deps,"dados",m("dados",observation)));return d;
 }
 void contingency()throws Exception {
  x.precheck("contingencia-dependencias-alvo-aninhado",false);var a=receive("CONT-A");var b=receive("CONT-B");Instant t1=Instant.now(),t2=Instant.now();String id1=x.round+"L1",id2=x.round+"L2";var d1=line(a,id1,t1,List.of());var d2=line(b,id2,t2,List.of(id1));x.ids.put("contingenciaObservacoesAtuais",m("L1",d1,"L2",d2));x.save();var l2=post("D29 L2antesL1 registro","/api/v1/contingencias",d2,"SUPERVISOR",200);var c=x.version(l2);c.put("modo","EXECUTAR");p.code("D29 dependencia ausente",post("D29 L2 nao fabrica L1","/api/v1/contingencias/"+l2.path("id").asLong()+"/conciliar",c,"SUPERVISOR",409),"DEPENDENCIA_AUSENTE");var l1=post("D29 L1 registro posterior preservaobservacao","/api/v1/contingencias",d1,"SUPERVISOR",200);c=x.version(l1);c.put("modo","EXECUTAR");post("D29 Operacao nao concilia","/api/v1/contingencias/"+l1.path("id").asLong()+"/conciliar",c,"OPERACAO",403);post("D29 L1executa alvoDTOaninhado","/api/v1/contingencias/"+l1.path("id").asLong()+"/conciliar",c,"SUPERVISOR",200);l2=get("/api/v1/contingencias/"+l2.path("id").asLong());c=x.version(l2);c.put("modo","EXECUTAR");var yes=post("D29 L2aposL1 umaexecucao","/api/v1/contingencias/"+l2.path("id").asLong()+"/conciliar",c,"SUPERVISOR",200);x.assertion("D29 L2replay nao duplicacontagem",yes.equals(post("D29 L2replay","/api/v1/contingencias/"+l2.path("id").asLong()+"/conciliar",c,"SUPERVISOR",200))&&j.balance().path("fisicoTotal").decimalValue().intValueExact()==10,"fisico10/efeitoUnico",yes);var changed=new LinkedHashMap<>(d1);changed.put("operacaoId",UUID.randomUUID().toString());changed.put("tipo","AJUSTE");p.code("D29 identidade global imutavel",post("D29 L1 troca tipo recusada","/api/v1/contingencias",changed,"SUPERVISOR",409),"FATO_CONTINGENCIA_DIVERGENTE");x.ids.put("contingenciaUnidades",List.of(a,b));x.save();
 }
 void closing()throws Exception {
  x.precheck("encerramento-impedimentos",false);String r="/api/v1/encerramentos/CLIENTE/"+x.clientId;var before=get(r+"/impedimentos");x.assertion("D29 encerramento identifica saldo",!before.path("impedimentos").isEmpty(),"impedimentos presentes",before);var pending=post("D29 solicitar cliente comremanescente",r+"/solicitar",x.version(before),"GESTOR",200);p.code("D29 encerramento saldo conservado",post("D29 inativarcliente409saldo",r+"/inativar",x.version(pending),"GESTOR",409),"ENCERRAMENTO_IMPEDIDO");x.assertion("D29 saldo10 clientependente",j.balance().path("fisicoTotal").decimalValue().intValueExact()==10&&get("/api/v1/clientes/"+x.clientId).path("situacao").asString().equals("ENCERRAMENTO_PENDENTE"),"10/ENCERRAMENTO_PENDENTE",get(r+"/impedimentos"));x.save();
 }
 void resume()throws Exception {
  x.precheck("contingencia-retoma-somente-fase-pendente",false);x.product=get("/api/v1/produtos/"+x.ids.get("produtoId"));x.pack=get("/api/v1/embalagens/"+x.ids.get("embalagemId"));
  var prior=x.json.readTree(Files.readAllBytes(x.evidence.resolve("d29-"+x.ids.get("retomadaDe")+"-http.json")));JsonNode registered=null;for(var c:prior.path("cases"))if(c.path("caso").asString().equals("D29 L2antesL1 registro")&&c.path("actual").asInt()==200)registered=c;
  if(registered==null)throw new IllegalStateException("D29_CONTINGENCIA_PARCIAL_AUSENTE");var observations=x.json.valueToTree(x.ids.get("contingenciaObservacoesAtuais"));var d1=observations.path("L1");var d2=observations.path("L2");x.preserveCapturedDates(d1,d1,Instant.parse(registered.path("instanteRespostaUtc").asString()));
  var l2=get("/api/v1/contingencias/"+registered.path("resposta").path("id").asLong());x.assertion("D29 dependencia conservada PENDENTE semefeito",l2.path("situacao").asString().equals("PENDENTE")&&l2.path("pendencia").asString().equals("DEPENDENCIA_AUSENTE")&&get("/api/v1/contagens?clienteId="+x.clientId+"&armazemId="+x.warehouseId).path("totalItens").asLong()==0,"PENDENTE/DEPENDENCIA_AUSENTE/contagens0",l2);
  var a=get("/api/v1/unidades-logisticas/"+d1.path("dados").path("dados").path("codigoUnidade").asString());var b=get("/api/v1/unidades-logisticas/"+d2.path("dados").path("dados").path("codigoUnidade").asString());
  var l1=post("D29 L1 registro somente fasefaltante","/api/v1/contingencias",d1,"SUPERVISOR",200);var cmd=x.version(l1);cmd.put("modo","EXECUTAR");post("D29 Operacao nao concilia","/api/v1/contingencias/"+l1.path("id").asLong()+"/conciliar",cmd,"OPERACAO",403);post("D29 L1executa alvoDTOaninhado","/api/v1/contingencias/"+l1.path("id").asLong()+"/conciliar",cmd,"SUPERVISOR",200);l2=get("/api/v1/contingencias/"+l2.path("id").asLong());cmd=x.version(l2);cmd.put("modo","EXECUTAR");var yes=post("D29 L2aposL1 umaexecucao","/api/v1/contingencias/"+l2.path("id").asLong()+"/conciliar",cmd,"SUPERVISOR",200);x.assertion("D29 L2replay nao duplicacontagem",yes.equals(post("D29 L2replay","/api/v1/contingencias/"+l2.path("id").asLong()+"/conciliar",cmd,"SUPERVISOR",200))&&get("/api/v1/contagens?clienteId="+x.clientId+"&armazemId="+x.warehouseId).path("totalItens").asLong()==2&&j.balance().path("fisicoTotal").decimalValue().intValueExact()==10,"2contagens/fisico10/efeitoUnico",yes);
  var changed=x.json.convertValue(d1,Map.class);changed.put("operacaoId",UUID.randomUUID().toString());changed.put("fonte",x.round+" fontealterada ficticia");p.code("D29 identidade global conteudo imutavel",post("D29 L1conteudodivergente409","/api/v1/contingencias",changed,"SUPERVISOR",409),"FATO_CONTINGENCIA_DIVERGENTE");x.ids.put("contingenciaUnidades",List.of(a,b));x.save();
 }
}
