import tools.jackson.databind.JsonNode;
import java.util.*;

/** Rejeicao/reabertura nativas de previsao atual, sem chamar isso aprovacao de ciclo encerrado. */
final class FinanceiroVersoesD29 {
 final EnsaioD29 x;final FinanceiroHttpD29 f;final PendenciasD29 p;
 FinanceiroVersoesD29(EnsaioD29 x){this.x=x;f=new FinanceiroHttpD29(x);p=new PendenciasD29(x);}
 JsonNode get(String name,String r)throws Exception{return x.call(name,"GET",r,null,"GESTOR",200);}
 JsonNode post(String n,String r,Object d,String role,int status)throws Exception{return x.call(n,"POST",r,d,role,status);}
 Map<String,Object> decide(JsonNode closure,int number){var d=x.version(closure);d.put("numero",number);return d;}
 void run()throws Exception {
  if(!x.ids.containsKey("retomadaDe")||!x.ids.containsKey("fechamentoPrevisaoId"))throw new IllegalStateException("D29_VERSOES_EXIGE_PREVISAO_REAL_EXISTENTE");x.precheck("financeiro-previsao-versoes",false);long id=((Number)x.ids.get("fechamentoPrevisaoId")).longValue();String route="/api/v1/fechamentos-cobranca/"+id;var current=get("D29 fechamento atual antesrejeicao",route);if(current.path("versaoAtual").asInt()==2){finishOnly(route,current);return;}if(!current.path("situacao").asString().equals("EM_REVISAO")||current.path("versaoAtual").asInt()!=1)throw new IllegalStateException("D29_VERSOES_FASE_JA_AVANCADA_RECUSADA");
  x.ids.put("oraculosSQL",EnsaioD29.m("F33parcial","Previsao v1=76 rejeitada; nova execucaoficticia coberta30→subtotal90+12/min0/GRIS4=106; reabertura v1SUPERADA/v2PENDENTE_REVISAO; mesma memoria/bytes/hash v1 originais. Sem aprovacao de ciclo fechado.","F39","Calculo76 antigo nao reescrito; novo106/hash novo; replays nao duplicamfato/calculo/versao; autorizacao corrente antesreplay.","limite","Ciclo real encerra08/10; emissao/desconhecido/creditoAPROVADO/EMITIDO nao provados por esta previsao."));x.save();var v1=get("D29 v1 original antes",route+"/versoes/1");get("D29 bytes v1 antes",route+"/versoes/1/demonstrativo");String originalBytes=String.valueOf(x.cases.getLast().get("corpoSHA256"));var d=decide(current,1);post("D29 Operacao nao rejeita",route+"/rejeicao",d,"OPERACAO",403);var rejected=post("D29 rejeicao futura comotratativa local",route+"/rejeicao",d,"GESTOR",200);x.assertion("D29 rejeicao replay snapshot unico",rejected.equals(post("D29 rejeicao replay",route+"/rejeicao",d,"GESTOR",200)),"REJEITADA/unico",rejected);
  var cfg=x.json.valueToTree(x.ids.get("financeiroConfiguracao"));for(var service:cfg.path("servicos"))if(service.path("codigo").asString().endsWith("COB"))f.covered=service;if(f.covered==null)throw new IllegalStateException("D29_SERVICO_COBERTO_FONTE_AUSENTE");f.pe=((Number)x.ids.get("pedidoEntradaId")).longValue();f.note=((Number)x.ids.get("notaId")).longValue();var fact=f.fact(f.covered,"VERSAO-C3");var c106=f.calculate("D29 previsao106 antesreabertura");f.numeric("novaexecucao90+12+4=106",c106,106,0,4);x.ids.put("calculo106",c106);x.ids.put("fatoVersaoC3",fact);x.save();
  d=decide(rejected.path("fechamento"),1);d.put("calculoId",c106.path("id").asLong());post("D29 Supervisor nao reabre",route+"/reabertura",d,"SUPERVISOR",403);var reopened=post("D29 reabertura v2previsao106",route+"/reabertura",d,"GESTOR",200);x.assertion("D29 reabertura replay v2unica",reopened.equals(post("D29 reabertura replay",route+"/reabertura",d,"GESTOR",200))&&get("D29 lista2versoes",route+"/versoes").size()==2,"2versoes/snapshotunico",reopened);post("D29 replayreabertura Opera403",route+"/reabertura",d,"OPERACAO",403);var geral=x.callToken("D29 replayreabertura GESTORgeral200","POST",route+"/reabertura",d,"GESTOR",x.token("GESTOR",EnsaioD29.m("wms_clientes",List.of())),200);x.assertion("D29 GESTOR geral snapshot preservado",geral.equals(reopened),reopened,geral);
  var old=get("D29 v1SUPERADA memoria original",route+"/versoes/1");get("D29 bytes v1 depois",route+"/versoes/1/demonstrativo");String after=String.valueOf(x.cases.getLast().get("corpoSHA256"));x.assertion("D29 F33 v1bytes/hash76 e v2review106",old.path("situacao").asString().equals("SUPERADA")&&old.path("conteudoHash").equals(v1.path("conteudoHash"))&&originalBytes.equals(after)&&old.path("saldo").decimalValue().intValueExact()==76&&reopened.path("versao").path("situacao").asString().equals("PENDENTE_REVISAO")&&reopened.path("versao").path("saldo").decimalValue().intValueExact()==106,"v1SUPERADA/bytesinalterados76/v2review106",EnsaioD29.m("v1",old,"v2",reopened,"bytesAntes",originalBytes,"bytesDepois",after));
  d=decide(reopened.path("fechamento"),2);p.code("D29 v2futuro continua naoaprovavel",post("D29 v2recusa corte real",route+"/aprovacao",d,"GESTOR",409),"PERIODO_NAO_ENCERRADO");x.ids.put("financeiroReaberturaPrevisao",reopened);x.save();
 }
 void finishOnly(String route,JsonNode current)throws Exception {
  var prior=x.json.readTree(java.nio.file.Files.readAllBytes(x.evidence.resolve("d29-"+x.ids.get("retomadaDe")+"-http.json")));JsonNode original=null,reopened=null,scope=null;String bytes=null;
  for(var c:prior.path("cases")){String name=c.path("caso").asString();if(name.equals("D29 v1 original antes"))original=c.path("resposta");if(name.equals("D29 bytes v1 antes"))bytes=c.path("corpoSHA256").asString();if(name.equals("D29 reabertura v2previsao106"))reopened=c.path("resposta");if(name.equals("D29 replayreabertura alcance403"))scope=c;}
  if(original==null||reopened==null||bytes==null||scope==null||scope.path("actual").asInt()!=200)throw new IllegalStateException("D29_V2_RETOMADA_SEM_PROVA_ORIGINAL");
  x.assertion("D29 corrigir oraculo GESTORgeral listas nao limitam replay",scope.path("resposta").equals(reopened),"GESTORgeral200/mesmosnapshot; Supervisor/Operacao403 anteriores preservados",scope.path("resposta"));
  var old=get("D29 v1SUPERADA GETcorrente sofaltante",route+"/versoes/1");var v2=get("D29 v2PENDENTE GETcorrente sofaltante",route+"/versoes/2");get("D29 bytes v1 depois sofaltante",route+"/versoes/1/demonstrativo");String now=String.valueOf(x.cases.getLast().get("corpoSHA256"));x.assertion("D29 F33 v1bytes/hash76 v2previsao106",old.path("situacao").asString().equals("SUPERADA")&&old.path("conteudoHash").equals(original.path("conteudoHash"))&&bytes.equals(now)&&old.path("saldo").decimalValue().intValueExact()==76&&v2.path("situacao").asString().equals("PENDENTE_REVISAO")&&v2.path("saldo").decimalValue().intValueExact()==106,"v1SUPERADA/bytespreservados76/v2review106",EnsaioD29.m("v1",old,"v2",v2,"bytesAntes",bytes,"bytesDepois",now));
  var pending=x.json.valueToTree(x.ids.get("calculoSemConfiguracao"));if(pending.path("id").asLong()<=0)throw new IllegalStateException("D29_CALCULO_PENDENTE_ORIGINAL_AUSENTE");var stillPending=get("D29 F39 GET original PENDENTE apos dadoscompletos106","/api/v1/calculos-cobranca/"+pending.path("id").asLong());x.assertion("D29 F39 pendente NULL snapshot preservado apos configuracao",stillPending.equals(pending)&&stillPending.path("total").isNull()&&stillPending.path("situacao").asString().equals("PENDENTE"),"PENDENTE/NULL/mesmoIDhashmemoria; novo106 distinto",stillPending);x.ids.put("calculoPendenteGETApos106",stillPending);
  var d=decide(current,2);p.code("D29 v2futuro naoaprovavel",post("D29 v2corte real somente faltante",route+"/aprovacao",d,"GESTOR",409),"PERIODO_NAO_ENCERRADO");x.ids.put("financeiroV1V2GETFinal",EnsaioD29.m("v1",old,"v2",v2));x.ids.put("oraculoGestorCorrigido","GESTOR tem alcance geral; lista vazia nao restringe. Nenhum novo replay HTTP sobre reabertura concluida; prova corrigida usa resposta ja obtida e GETs.");x.save();
 }
}
