import tools.jackson.databind.JsonNode;
import java.time.*;
import java.util.*;
import java.math.BigDecimal;

/** Datas atuais e previsao real. Nao fabrica ciclo passado para obter aprovacao. */
final class FinanceiroHttpD29 {
 final EnsaioD29 x;final JornadasD29 j;long pe,note;JsonNode covered,other;
 FinanceiroHttpD29(EnsaioD29 x){this.x=x;j=new JornadasD29(x);}
 static Map<String,Object>m(Object...v){return EnsaioD29.m(v);}
 JsonNode post(String n,String r,Object b,String role,int e)throws Exception{return x.call(n,"POST",r,b,role,e);}
 JsonNode service(String suffix,String type,String unit)throws Exception{var d=x.command();d.putAll(m("codigo",x.round+suffix,"descricao",x.round+" PRECO FICTICIO SEM ACEITE COMERCIAL "+suffix,"tipo",type,"unidade",unit));return post("D29 servicoFICTICIO"+suffix,"/api/v1/servicos-cobranca",d,"GESTOR",200);}
 JsonNode calculate(String name)throws Exception{LocalDate today=LocalDate.now();var d=x.command();d.putAll(m("clienteId",x.clientId,"armazemId",x.warehouseId,"periodoInicio",today.toString(),"periodoFim",today.plusDays(1).toString()));var c=post(name,"/api/v1/calculos-cobranca",d,"SUPERVISOR",200);x.assertion(name+" replay unico",c.equals(post(name+" replay","/api/v1/calculos-cobranca",d,"SUPERVISOR",200)),c,"unico");return c;}
 void run()throws Exception{
  if(x.ids.containsKey("retomadaDe")) {
   var prior=x.json.readTree(java.nio.file.Files.readAllBytes(x.evidence.resolve("d29-"+x.ids.get("retomadaDe")+"-http.json")));JsonNode c76=null;
   for(var c:prior.path("cases"))if(c.path("caso").asString().equals("D29 F22 previsao76")&&c.path("actual").asInt()==200)c76=c.path("resposta");
   if(c76==null)throw new IllegalStateException("D29_FINANCEIRO_CALCULO76_PARCIAL_AUSENTE");
   finish(x.json.valueToTree(x.ids.get("calculo66")),c76);return;
  }
  x.ids.put("oraculosSQL",m("F21","previsao atual subtotal30+12 minimo20 GRIS4 total66; fisico100NAOUNITIZADO valor400","F22","novaexecucao coberta30: subtotal60+12 minimo0 GRIS4 total76; calculo66 originalimutuavel","F39","novoID/hash aposfato novo comGEToriginal66 inalterado; replaymesmosnapshot","corte","fechamento futuro emrevisao; aprovar409PERIODO_NAO_ENCERRADO; nao contaaprovacao real/externa","datas","contrato/tabela/nota/chegada/execucao atuais; nenhuma vigencia ou fato passado fabricado"));x.save();j.cadastros();x.precheck("financeiro-configuracao-ausente",false);var missing=calculate("D29 previsao semcontrato PENDENTE");x.assertion("D29 ausencianaozero",missing.path("situacao").asString().equals("PENDENTE")&&missing.path("total").isNull(),"PENDENTE/totalNULL",missing);x.ids.put("calculoSemConfiguracao",missing);x.save();
  covered=service("COB","ADICIONAL","VEICULO");other=service("FORA","ADICIONAL","VEICULO");var storage=service("ARM","ARMAZENAGEM","POSICAO_DIA");LocalDate today=LocalDate.now();var d=x.command();d.putAll(m("armazemId",x.warehouseId,"codigo",x.round+"TAB","descricao",x.round+" precosFICTICIOS30/12/7","tipo","PADRAO","vigenciaInicio",today.toString(),"itens",List.of(m("servicoId",covered.path("id").asLong(),"categoria","","preco",30),m("servicoId",other.path("id").asLong(),"categoria","","preco",12),m("servicoId",storage.path("id").asLong(),"categoria","","preco",7))));var table=post("D29 tabela atual30/12/7","/api/v1/tabelas-cobranca",d,"GESTOR",200);d=x.command();d.putAll(m("clienteId",x.clientId,"armazemId",x.warehouseId,"tabelaId",table.path("id").asLong(),"vigenciaInicio",today.toString()));var link=post("D29 vinculoatual","/api/v1/vinculos-tabela",d,"GESTOR",200);
  d=x.command();d.putAll(m("clienteId",x.clientId,"armazemId",x.warehouseId,"vigenciaInicio",today.toString(),"fuso",ZoneId.systemDefault().getId(),"moeda","BRL","modalidadeCiclo","DIAS_CORRIDOS","duracaoDias",1,"minimoModo","APLICAVEL","minimoValor",50,"minimoProporcao","INTEGRAL","servicosMinimo",List.of(covered.path("id").asLong()),"grisModo","APLICAVEL","grisPercentual",1,"grisBase","VALOR_ESTOQUE_PICO","grisPeriodicidade","DIARIA","grisProporcao","INTEGRAL"));var contract=post("D29 contratoficticioatual minimo50/GRIS1","/api/v1/contratos-cobranca",d,"GESTOR",200);x.ids.put("financeiroConfiguracao",m("tabela",table,"vinculo",link,"contrato",contract,"servicos",List.of(covered,other,storage)));x.save();
  x.precheck("financeiro-entrada-ainda-naounitizada",false);pe=post("D29 pedidoentradafinanceiro","/api/v1/pedidos-entrada",m("clienteId",x.clientId,"armazemId",x.warehouseId,"referencia",x.round+"FIN"),"OPERACAO",201).path("id").asLong();post("D29 nota100valor400 atual",j.pe(pe)+"/notas",m("versao",j.pv(pe),"serie",1,"numero",x.nextDocumentNumber(),"emissao",today.toString(),"itens",List.of(m("numeroItem",1,"produtoId",x.ids.get("produtoId"),"quantidadePrevista",100,"valorMercadoria",400))),"OPERACAO",200);post("D29 conferenciafinanceira",j.pe(pe)+"/iniciar-conferencia",m("versao",j.pv(pe),"motivo",x.round+" conferir100ficticios"),"OPERACAO",200);j.arrival(pe,100,Instant.now());post("D29 efetivar100sem unitizar",j.pe(pe)+"/efetivacao",m("versao",j.pv(pe),"aceitarDivergencias",false,"motivo",x.round+" quantidade100 confirmada real"),"SUPERVISOR",200);note=j.get(j.pe(pe)).path("notas").get(0).path("id").asLong();x.ids.put("pedidoEntradaId",pe);x.ids.put("notaId",note);x.save();var balance=j.balance();x.assertion("D29 fisico100pendente100disp0",balance.path("fisicoTotal").decimalValue().intValueExact()==100&&balance.path("pendenteUnitizacao").decimalValue().intValueExact()==100&&balance.path("disponivel").decimalValue().signum()==0,"100/100/0",balance);
  var f1=fact(covered,"C1");var f2=fact(other,"F1");var c66=calculate("D29 F21 previsao66");numeric("F21 minimo20 total66",c66,66,20,4);x.ids.put("calculo66",c66);x.ids.put("fatosFinanceiros",new ArrayList<>(List.of(f1,f2)));x.save();
  var f3=fact(covered,"C2");var c76=calculate("D29 F22 previsao76");numeric("F22 minimo0 total76",c76,76,0,4);x.ids.put("fatosFinanceiros",List.of(f1,f2,f3));finish(c66,c76);
 }
 void finish(JsonNode c66,JsonNode c76)throws Exception {
  x.precheck("financeiro-GET-original-e-corte-futuro",false);
  x.assertion("D29 F39 original66naoreescrito",c66.equals(x.call("D29 F39 GEToriginal66 perfilSupervisor","GET","/api/v1/calculos-cobranca/"+c66.path("id").asLong(),null,"SUPERVISOR",200))&&c76.path("id").asLong()!=c66.path("id").asLong()&&!c76.path("entradasHash").equals(c66.path("entradasHash")),"original66/nova76/hashdiferente",c76);x.ids.put("calculo76",c76);x.save();LocalDate today=LocalDate.now();Map<String,Object>d;
  var prep=x.command();prep.put("calculoId",c76.path("id").asLong());var f=post("D29 preparoprevisao76","/api/v1/fechamentos-cobranca",prep,"GESTOR",200);long fid=f.path("fechamento").path("id").asLong();d=x.version(f.path("fechamento"));d.put("numero",f.path("versao").path("numero").asInt());var no=post("D29 futuroNAOaprova","/api/v1/fechamentos-cobranca/"+fid+"/aprovacao",d,"GESTOR",409);x.assertion("D29 corte futuro explicitopendente",no.path("codigo").asString().equals("PERIODO_NAO_ENCERRADO"),"PERIODO_NAO_ENCERRADO",no);x.ids.put("fechamentoPrevisaoId",fid);x.ids.put("limiteAprovacaoNativa","Ciclo configurado atual encerra somente em "+today.plusDays(1)+" nofuso "+ZoneId.systemDefault()+"; nao fabricarvigencia/fatos anteriores nem mudarClock. Preparacao/previsao nao e aprovacao.");x.save();
 }
 void numeric(String name,JsonNode c,int total,int min,int gris)throws Exception{x.assertion("D29 "+name,c.path("situacao").asString().equals("COMPLETO")&&c.path("total").decimalValue().compareTo(BigDecimal.valueOf(total))==0&&c.path("minimoCalculado").decimalValue().compareTo(BigDecimal.valueOf(min))==0&&c.path("grisCalculado").decimalValue().compareTo(BigDecimal.valueOf(gris))==0,"COMPLETO/min="+min+"/GRIS="+gris+"/total="+total,c);}
 JsonNode fact(JsonNode s,String ref)throws Exception{var d=x.command();d.putAll(m("clienteId",x.clientId,"armazemId",x.warehouseId,"servicoId",s.path("id").asLong(),"origem","MANUAL","pedidoEntradaId",pe,"produtoId",x.ids.get("produtoId"),"referenciaExecucao",x.round+ref,"executadoEm",Instant.now().toString(),"quantidade",1,"categoria","","cotas",List.of(m("notaId",note,"cota",1)),"criterioRateio",x.round+" execucaoficticia notadeorigem"));var f=post("D29 fatoexecucao"+ref,"/api/v1/fatos-servico",d,"SUPERVISOR",200);x.assertion("D29 fato replay"+ref,f.equals(post("D29 replayfato"+ref,"/api/v1/fatos-servico",d,"SUPERVISOR",200)),f,"snapshotunico");return f;}
}
