import tools.jackson.databind.JsonNode;
import java.time.*;
import java.util.*;

/** Fases novas da familia47: devolucao da retirada100 e cancelamento separado ficticio. */
final class RetornosD29 {
 final EnsaioD29 x;final JornadasD29 j;final PendenciasD29 p;
 RetornosD29(EnsaioD29 x){this.x=x;j=new JornadasD29(x);p=new PendenciasD29(x);}
 static Map<String,Object> m(Object...v){return EnsaioD29.m(v);}
 JsonNode get(String n,String r)throws Exception{return x.call(n,"GET",r,null,"SUPERVISOR",200);}
 JsonNode post(String n,String r,Object d,String role,int code)throws Exception{return x.call(n,"POST",r,d,role,code);}
 Map<String,Object> note(){return m("emitenteCnpj",x.round+"DDD","serie","1","numero",Long.toString(x.nextDocumentNumber()),"emissao",LocalDate.now(ZoneOffset.UTC).toString());}
 void qty(String label,int physical,int reserved)throws Exception{var b=j.balance();x.assertion(label,b.path("fisicoTotal").decimalValue().intValueExact()==physical&&b.path("reservado").decimalValue().intValueExact()==reserved,"fisico"+physical+"/reserva"+reserved,b);}
 void run()throws Exception {
  if(!x.ids.containsKey("retomadaDe")||!x.ids.containsKey("retirada")||x.ids.containsKey("devolucaoNova40"))throw new IllegalStateException("D29_RETORNO_EXIGE_FASE_FALTANTE_UNICA");x.precheck("retornos-novos",false);x.product=j.get("/api/v1/produtos/"+x.ids.get("produtoId"));x.pack=j.get("/api/v1/embalagens/"+x.ids.get("embalagemId"));
  x.ids.put("oraculosSQL",m("fontes",List.of("docs/27-separacao-retirada-retornos-e-avaria.md:11-15","D29-VIG-P16"),"esperado","Original retirado100 e baixa imutaveis; retorno40 cria novo PE efetivado nao unitizado/FIFOoriginal com chegada real nova, fisico900->940; excesso61recusa409 mantendo40 e baixa100. Novo recebimento60 separado/documentoativo impede retorno; cancelamento fiscal nao libera60 automaticamente; retorno interno60 fecha reserva e pedido, sem novo recebimento/baixa, fisico1000. Replays snapshotunico/perfis atuais.","limite","Documentos ficticios declarados localmente, nenhuma emissao externa/aceite fiscal; este caso nao altera retirada concluida."));x.save();
  long old=((Number)x.ids.get("pedidoSaidaId")).longValue();String r="/api/v1/pedidos-saida/"+old;var original=get("D29 retirada historica antes devolucao",r+"/expedicao");if(!original.path("pedido").path("situacao").asString().equals("RETIRADO")||original.path("baixas").size()!=1||!original.path("devolucoes").isEmpty())throw new IllegalStateException("D29_DEVOLUCAO_PRECONDICAO_NAO_LIMPA");qty("D29 antesretorno fisico900",900,0);var baixa=original.path("baixas").get(0);
  var d=x.version(original.path("pedido"));d.putAll(m("referencia",x.round+"DEV40","nota",note(),"chegadaReal",Instant.now().toString(),"itens",List.of(m("baixaId",baixa.path("id").asLong(),"quantidade",40,"quantidadeAvariada",0))));post("D29 Operacao nao devolve",r+"/devolucoes",d,"OPERACAO",403);var returned=post("D29 devolucao40 nova entrada",r+"/devolucoes",d,"SUPERVISOR",200);x.ids.put("devolucaoNova40",returned);x.save();x.assertion("D29 devolucao40 replay snapshot unico",returned.equals(post("D29 replaydevolucao40",r+"/devolucoes",d,"SUPERVISOR",200)),returned,"unico");long pe=returned.path("pedidoEntradaId").asLong();if(pe<=0)throw new IllegalStateException("D29_DEVOLUCAO_ID_NOVO_AUSENTE");var currentPe=get("D29 novo PE retorno40 GET",j.pe(pe));var entries=get("D29 retorno40 confirmado ainda nao unitizado",j.pe(pe)+"/entradas");var current=get("D29 retirada preservada GET",r+"/expedicao");x.assertion("D29 devolucao conserva baixa100/FIFOoriginal",current.path("baixas").equals(original.path("baixas"))&&current.path("retiradaEm").equals(original.path("retiradaEm"))&&current.path("devolucoes").size()==1&&current.path("devolucoes").get(0).path("quantidade").decimalValue().intValueExact()==40&&current.path("devolucoes").get(0).path("dataFifo").equals(baixa.path("dataFifo"))&&entries.path("itens").size()==1,"baixa100/retirada/FIFOintactos/novoPE40",m("original",original,"agora",current,"entrada",currentPe,"entradas",entries));qty("D29 fisico940 retorno nao unitizado",940,0);
  var excess=x.version(current.path("pedido"));excess.putAll(m("referencia",x.round+"EXCESSO61","nota",note(),"chegadaReal",Instant.now().toString(),"itens",List.of(m("baixaId",baixa.path("id").asLong(),"quantidade",61,"quantidadeAvariada",0))));p.code("D29 devolucao saldo60 nao aceita61",post("D29 excesso61recusa",r+"/devolucoes",excess,"SUPERVISOR",409),"DEVOLUCAO_EXCEDIDA");x.assertion("D29 excesso nao altera retirada/retornos",current.equals(get("D29 retorno GETaposrecusa",r+"/expedicao")),current,get("D29 retorno GETaposrecusa2",r+"/expedicao"));qty("D29 excesso conserva940",940,0);
  cancelSeparated();x.save();
 }
 void cancelSeparated()throws Exception {
  x.precheck("retorno-interno-separado",false);long pe=j.entry("CANCELAMENTO60",60);j.arrival(pe,60,Instant.now());post("D29 novo recebimento60 para retornointerno",j.pe(pe)+"/efetivacao",m("versao",j.pv(pe),"aceitarDivergencias",false,"motivo",x.round+"60 para cancelamento ficticio"),"SUPERVISOR",200);long en=j.get(j.pe(pe)+"/entradas").path("itens").get(0).path("id").asLong();var u=j.unitize(pe,en,60);var storage=j.address("RCARM","ARMAZENAGEM");post("D29 endereco novo60",j.unit(u)+"/movimentos",j.move(u,storage),"OPERACAO",200);u=j.actual(u);qty("D29 recebido60 aumenta940a1000",1000,0);
  var order=j.order("CANCELAR60",60);var proposal=x.version(order);proposal.put("selecoes",List.of(m("unidadeId",u.path("id").asLong(),"quantidade",60)));var just=post("D29 escolher novo60 sem alterar reserva antiga",j.ps(order)+"/justificativas-fifo",proposal,"SUPERVISOR",200);var reserve=x.version(just.path("pedido"));reserve.put("justificativaId",proposal.get("operacaoId"));order=post("D29 reserva nova60 excepcional",j.ps(order)+"/reserva",reserve,"SUPERVISOR",200).path("pedido");long rid=order.path("reservas").get(0).path("id").asLong();var label=j.get(j.unit(u)+"/etiqueta");var d=x.version(order);d.putAll(m("reservaId",rid,"codigoLido",u.path("codigo").asString(),"revisaoConteudo",label.path("versaoConteudo").asLong()));order=post("D29 leitura60 nova",j.ps(order)+"/leituras",d,"OPERACAO",200).path("expedicao").path("pedido");var sep=j.address("RCSEP","SEPARACAO");d=x.version(order);d.put("destinacao",m("reservaId",rid,"destinos",j.destinations(sep)));order=post("D29 separar60 nova",j.ps(order)+"/separacoes",d,"OPERACAO",200).path("expedicao").path("pedido");
  d=x.version(order);d.putAll(m("origem","NOTAZZ","natureza","RETORNO_MERCADORIA","nota",note(),"protocolo",x.round+" FICTICIO SEM EMISSAO","coberturas",List.of(m("reservaId",rid,"notaOrigemId",order.path("reservas").get(0).path("notaOrigemId").asLong(),"sku",x.product.path("sku").asString(),"quantidade",60))));var doc=post("D29 documento ficticio cancelavel60",j.ps(order)+"/documentos",d,"SUPERVISOR",200).path("expedicao");order=doc.path("pedido");x.ids.put("pedidoRetornoInterno60",order.path("id").asLong());x.save();
  var cmd=x.version(order);cmd.put("unidades",List.of(m("reservaId",rid,"destinos",j.destinations(storage))));p.code("D29 documentoativo impede retornointerno",post("D29 retorno60 comdocumentoativo",j.ps(order)+"/retorno-interno",cmd,"SUPERVISOR",409),"DOCUMENTO_ATIVO");x.assertion("D29 recusa documentoativo nao move/reserva",doc.equals(get("D29 separado GETaposrecusa",j.ps(order)+"/expedicao")),doc,get("D29 separado GETaposrecusa2",j.ps(order)+"/expedicao"));qty("D29 documentoativo fis1000 reserva60",1000,60);
  long did=doc.path("documentos").get(0).path("id").asLong();var cancel=x.version(order);post("D29 Operacao nao cancela fiscal",j.ps(order)+"/documentos/"+did+"/cancelamento",cancel,"OPERACAO",403);var cancelled=post("D29 cancelar somente documento60",j.ps(order)+"/documentos/"+did+"/cancelamento",cancel,"SUPERVISOR",200);x.assertion("D29 replay cancelardocumento unico",cancelled.equals(post("D29 replay cancelardocumento60",j.ps(order)+"/documentos/"+did+"/cancelamento",cancel,"SUPERVISOR",200)),cancelled,"unico");qty("D29 fiscalcancelado preserva fisico/reserva",1000,60);order=cancelled.path("expedicao").path("pedido");
  var beforePe=j.get("/api/v1/pedidos-entrada?clienteId="+x.clientId+"&armazemId="+x.warehouseId+"&tamanho=100");cmd=x.version(order);cmd.put("unidades",List.of(m("reservaId",rid,"destinos",j.destinations(storage))));post("D29 Operacao nao confirma retorno",j.ps(order)+"/retorno-interno",cmd,"OPERACAO",403);var yes=post("D29 retornointerno60 cancela reserva atomicamente",j.ps(order)+"/retorno-interno",cmd,"SUPERVISOR",200);x.assertion("D29 replay retornointerno snapshot",yes.equals(post("D29 replay retornointerno60",j.ps(order)+"/retorno-interno",cmd,"SUPERVISOR",200)),yes,"unico");x.assertion("D29 retornointerno sem novo PE nem baixa",yes.path("expedicao").path("pedido").path("situacao").asString().equals("CANCELADO")&&yes.path("expedicao").path("baixas").isEmpty()&&beforePe.equals(j.get("/api/v1/pedidos-entrada?clienteId="+x.clientId+"&armazemId="+x.warehouseId+"&tamanho=100")),"CANCELADO/baixas0/mesmosPE",yes);qty("D29 retorno final1000 reserva0",1000,0);x.ids.put("retornoInterno60",yes);x.ids.put("pedidoEntradaRetornoExterno40",x.json.valueToTree(x.ids.get("devolucaoNova40")).path("pedidoEntradaId").asLong());x.save();
 }
}
