[CmdletBinding()]
param()
$ErrorActionPreference='Stop'
$backend=(Resolve-Path "$PSScriptRoot/../..").Path
$root=(Resolve-Path "$backend/..").Path
$utf8=[Text.UTF8Encoding]::new($false)
function Read-Json([string]$path){[IO.File]::ReadAllText($path)|ConvertFrom-Json}
function Write-Json([string]$name,$value){[IO.File]::WriteAllText((Join-Path $backend "evidencias/$name"),($value|ConvertTo-Json -Depth 14),$utf8)}
function Write-Md([string]$name,$lines){[IO.File]::WriteAllText((Join-Path $backend "evidencias/$name"),($lines -join "`n")+"`n",$utf8)}
function Cell($value){([string]$value).Replace('|','/').Replace("`r",' ').Replace("`n",' ')}
function Sql-Link([string]$value){$parts=$value -split ';',2;$path=$parts[0].Trim();$suffix=if($parts.Count -gt 1){'; '+(Cell $parts[1])}else{''};$url=if($path.StartsWith('orchestracao/')){'../../'+$path}elseif($path.StartsWith('backend/evidencias/')){$path.Substring(19)}else{$path};'['+[IO.Path]::GetFileName($path)+']('+$url+')'+$suffix}
$base=Read-Json (Join-Path $backend 'evidencias/d26-matriz.json')
$baseRules=Read-Json (Join-Path $backend 'evidencias/d26-regras.json')
$rounds=@();$all=@();$asserts=@();$offline=@()
foreach($f in @(Get-ChildItem (Join-Path $backend 'evidencias/d27-D27*-http.json')|Sort-Object Name)){
 $j=Read-Json $f.FullName
 if($j.fase -like 'offline*' -or $j.ids.etapa -eq 'offline'){$offline+=@([ordered]@{rodada=[string]$j.rodada;arquivo=$f.Name;casos=$j.cases.Count});continue}
 $http=@($j.cases|Where-Object {$_.metodo});$ass=@($j.cases|Where-Object {-not $_.metodo})
 $rounds+=@([ordered]@{rodada=[string]$j.rodada;fase=[string]$j.fase;etapa=[string]$j.ids.etapa;retomadaDe=[string]$j.ids.retomadaDe;arquivo=$f.Name;http=$http.Count;assertivas=$ass.Count;falhasHTTP=@($http|Where-Object {$_.estado -eq 'falhou'}).Count;falhasAssertivas=@($ass|Where-Object {$_.estado -eq 'falhou'}).Count;bloqueio=[string]$j.bloqueio;jarSha256=[string]$j.ids.jarSha256;jarPid=$j.ids.jarPid;porta=$j.ids.porta;issuerPorta=$j.ids.issuerPorta;jarEncerrado=$j.ids.jarEncerrado;issuerEncerrado=$j.ids.issuerEncerrado;portasLivresBindImediato=$j.ids.portasLivres;witnessSQL=$j.ids.witnessSQL})
 $idx=0
 foreach($c in $j.cases){$idx++
  $classificacao='HTTP previsto confrontado';$causa='Contrato e resposta na fonte do caso'
  if(-not $c.metodo){$classificacao='assertiva de conteudo';if($c.estado -eq 'falhou'){$classificacao='recusa historica da guarda de retomada';$causa='D27B2457D43 leu fixture ja reservada; interrompeu antes de gate/POST, sem nova mutacao'}}
  elseif($c.expected -is [string] -and $c.expected -match 'um 200 outro 409'){$classificacao='requisicao de par concorrente';$causa='Confronto conjunto200/409+GET/replay; witness da propria rodada em fonteSQL separada. D279E93BDC2 offline/flagfalse; D2748A39681 online/flagtrue'}
  elseif($c.estado -eq 'falhou'){
   switch -Regex ([string]$c.caso){
    '^AC13 aplica'{$classificacao='defeito backend corrigido';$causa='CHECK localizacao no ajuste zero; rollback e fix conservacao historica, HTTP/SQL posteriores';break}
    '^RN22 limite extremo'{$classificacao='defeito backend corrigido';$causa='Overflow int precision-scale antes agregacao; cast long red/green e novo JAR';break}
    '^RN22 limite numerico 100E'{$classificacao='defeito backend corrigido';$causa='stripTrailingZeros antes faixa estourava escala; guarda long antecipada red/green e novo JAR';break}
    '^RN23 FIFO chegada parcial0'{$classificacao='erro roteiro payload';$causa='Campo motivo nao existe em RegistrarChegada; removido somente do helper, mesma fixture retomada';break}
    '^RN08 conflito tabela especifica$'{$classificacao='erro roteiro expected';$causa='Codigos distintos de tabelas independentes sao permitidos; conflito real TABELA_DUPLICADA ou vinculo VIGENCIA_SOBREPOSTA';break}
    '^RN17 reversao explicita Supervisor$'{$classificacao='erro roteiro rota inexistente';$causa='Canonica /reversao-reserva; mesma UUID recusada404 depois aplicada/replay200';break}
    '^RN08 GET vinculo especifico final$'{$classificacao='erro roteiro rota inexistente';$causa='GET canonico /vinculos-tabela por clienteId/armazemId retorna lista, nao GET individual';break}
    default{$classificacao='falha historica a confrontar';$causa='Consultar fonte; nao classificar genericamente como backend'}
   }
  }elseif($c.caso -match '^RN22 limite numerico'){$classificacao='recusa numerica prevista aprovada';$causa='Faixa DECIMAL19,6 antes normalizacao/agregacao; GET sem novo pedido e SELECT focal proprio'}
  elseif($c.actual -ge 400){$classificacao='recusa prevista aprovada';$causa=[string]$c.resposta.codigo}
  $record=[pscustomobject][ordered]@{rodada=[string]$j.rodada;arquivo=$f.Name;jarSha256=[string]$j.ids.jarSha256;indice=$idx;caso=[string]$c.caso;metodo=[string]$c.metodo;rota=[string]$c.rota;perfil=[string]$c.perfil;expected=$c.expected;actual=$c.actual;estado=[string]$c.estado;classificacao=$classificacao;causaConfrontada=$causa;cookiePresente=$c.cookiePresente;segredoPresente=$c.segredoPresente;requestIdPresente=$c.requestIdPresente}
  if($c.metodo){$all+=@($record)}else{$record.actual='conteúdo e assertiva na fonte';$asserts+=@($record)}
 }
}
$extra=[pscustomobject]@{id='E161';controller='PedidoSaidaController';metodo='POST';rota='/api/v1/pedidos-saida/xml';documentos='24; RN22/03; Q13/10; AC02/11; d27-rn22-contrato.md';regras='RN22,RN29,AC02,AC11';positivoHTTP=$false}
$inventory=@($base.matriz)+@($extra);$rows=@();$mapped=[Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
foreach($e in $inventory){
 $pattern='^'+([regex]::Escape([string]$e.rota)-replace '\\\{[^}]+\}','[^/?]+')+'$'
 $cases=@($all|Where-Object {$_.metodo -eq $e.metodo -and ($_.rota -split '\?')[0] -match $pattern})
 foreach($c in $cases){[void]$mapped.Add($c.arquivo+'|'+$c.indice)}
 $pos=@($cases|Where-Object {$_.actual -ge 200 -and $_.actual -lt 300 -and $_.estado -ne 'falhou'})
 $gets=@($cases|Where-Object {$_.metodo -eq 'GET' -and $_.estado -eq 'aprovado'})
 $rows+=@([ordered]@{id=[string]$e.id;controller=[string]$e.controller;metodo=[string]$e.metodo;rota=[string]$e.rota;documentos=[string]$e.documentos;regras=[string]$e.regras;positivoHistoricoD26=[bool]$e.positivoHTTP;fonteHistoricaD26=if($e.id -ne 'E161'){'d26-matriz.json; localizar '+$e.id}else{$null};positivoAtualD27=($pos.Count -gt 0);positivoCombinado=([bool]$e.positivoHTTP -or $pos.Count -gt 0);perfisExercitados=@($cases.perfil|Sort-Object -Unique);perfisCom2xx=@($pos.perfil|Sort-Object -Unique);perfisCom403=@($cases|Where-Object {$_.actual -eq 403}|ForEach-Object {$_.perfil}|Sort-Object -Unique);casosD27=$cases;GETsD27=$gets;estado=if($cases.Count){'casos atuais confrontados; limites por regra'}else{'não reexecutado D27; prova D26 preservada, sem nova alteração nesta rota'};limite='Positivo HTTP não certifica todas as variantes/regra ou persistência SQL. Casos e assertivas de conteúdo estão nos JSONs de rodada; SQL tem recorte próprio por família/IDs.'})
}
$unmapped=@($all|Where-Object {-not $mapped.Contains($_.arquivo+'|'+$_.indice)})
foreach($c in $unmapped){if($c.classificacao -eq 'erro roteiro rota inexistente'){$c.classificacao='erroRoteiroforaAPIinventario';$c.causaConfrontada+='; 404 historico fora das 161 rotas, nao adicionar endpoint'}}
$pairs=@($all|Where-Object {$_.expected -is [string] -and $_.expected -match 'um 200 outro 409'})
$counts=[ordered]@{rodadas=$rounds.Count;http=$all.Count;httpAprovadasIndividualmente=@($all|Where-Object {$_.estado -eq 'aprovado'}).Count;httpRequisicoesParesConcorrentes=$pairs.Count;httpFalhasHistoricas=@($all|Where-Object {$_.estado -eq 'falhou'}).Count;assertivas=$asserts.Count;assertivasAprovadas=@($asserts|Where-Object {$_.estado -eq 'aprovado'}).Count;assertivasFalharam=@($asserts|Where-Object {$_.estado -eq 'falhou'}).Count;requestIdValidado=@($all|Where-Object {$_.requestIdPresente -eq $true}).Count;requestIdAusenciaObservada=@($all|Where-Object {$_.requestIdPresente -eq $false}).Count;requestIdNaoAvaliado=@($all|Where-Object {$null -eq $_.requestIdPresente}).Count;cookieObservado=@($all|Where-Object {$_.cookiePresente -eq $true}).Count;segredoObservado=@($all|Where-Object {$_.segredoPresente -eq $true}).Count;endpointsInventariados=$rows.Count;endpointsComPositivoD27=@($rows|Where-Object {$_.positivoAtualD27}).Count;endpointsComPositivoCombinado=@($rows|Where-Object {$_.positivoCombinado}).Count;httpNaoMapeado=$unmapped.Count}
$counts.httpDefeitosBackendHistoricosCorrigidos=@($all|Where-Object {$_.classificacao -eq 'defeito backend corrigido'}).Count
$counts.httpDivergenciasRoteiroHistoricas=@($all|Where-Object {$_.estado -eq 'falhou' -and $_.classificacao -match '^erro'}).Count
$matrix=[ordered]@{utc=[DateTime]::UtcNow.ToString('o');demanda='D27';backendTotalAprovado=$false;historiaD26Preservada=$true;ACPropostasNaoHomologadas=$true;contagens=$counts;rodadas=$rounds;offlineSeparado=$offline;matriz=$rows;assertivasConteudo=$asserts;httpNaoMapeado=$unmapped;limite='161 rotas positivas combinadas, se atingido, é cobertura de endpoint e não aceite de todas regras/variantes ou homologação. SQL não é certificado genérico por API.'}
Write-Json 'd27-matriz.json' $matrix
$md=@('# D27 — matriz objetiva HTTP','',('Gerada UTC '+$matrix.utc+'. D26 intacta. `backendTotalAprovado=false`; AC continuam propostas não homologadas.'),'',('HTTP novos: '+$counts.http+'; aprovados individualmente '+$counts.httpAprovadasIndividualmente+'; requisições de pares '+$counts.httpRequisicoesParesConcorrentes+'; falhas históricas '+$counts.httpFalhasHistoricas+'. Assertivas de conteúdo: '+$counts.assertivas+'/'+$counts.assertivasFalharam+' falhas. Checks offline separados.'),'',('Rotas: '+$counts.endpointsInventariados+'; positivo D27 '+$counts.endpointsComPositivoD27+'; positivo combinado D26/D27 '+$counts.endpointsComPositivoCombinado+'. E001–E160 estáveis; E161 criação XML.'),'','[JSON completo por endpoint/caso](d27-matriz.json) | [Regras e limites](d27-regras.md). Cada arquivo de rodada conserva payload/resposta e GET, inclusive recusas/tentativas. Pares concorrentes dependem de assertiva conjunta e witness SQL próprio; HTTP200/409 isolado não basta.','','| ID / documento / regra | Método e rota | D26 / D27 positivo | Perfis aceitos / recusados | Provas D27 expected→actual |','|---|---|---|---|---|')
foreach($r in $rows){$proof=@($r.casosD27|Select-Object -First 4|ForEach-Object {'['+ (Cell $_.caso)+']('+ $_.arquivo+') caso#'+$_.indice+' '+[string]$_.expected+'→'+[string]$_.actual});if(-not $proof.Count){$proof=@('D26 por ID em d26-matriz.json; não reexecutado (nenhuma mudança local)')};$md+=('|'+$r.id+' docs'+(Cell $r.documentos)+' '+(Cell $r.regras)+'|'+$r.metodo+' '+$r.rota+'|'+$r.positivoHistoricoD26+'/'+$r.positivoAtualD27+'|'+($r.perfisCom2xx -join ',')+' / '+($r.perfisCom403 -join ',')+'|'+($proof -join '; ')+'|')}
Write-Md 'd27-matriz.md' $md
$rules=@()
foreach($r in $baseRules.matriz){
 $endpoints=@($rows|Where-Object {($_.regras -split ',') -contains $r.regra})
 $casePatterns=@{
  RN22='^RN22|^XML'; AC13='^AC13'; RN08='^RN08'; RN15='^RN15'; RN17='^RN17'; RN23='^RN23 FIFO';
  RN14='^AC13|^RN17'; RN21='^AC04|^AC08'; AC07='^BE13|^RN27'; RN24='^concorrencia|^concorrência|^RN23 FIFO reserva'; RN25='^AC13'; AC14='^AC13';
  AC04='^AC04'; AC06='^AC06'; AC08='^AC08'; RN27='^RN27|^BE13';
  RN20='^filtro estoque|^paginação|^AC13 contagens|^RN22 pedidos'; RN28='página|pagina|filtro|limite101|conteúdo/metadados|overflow';
  AC11='^RN22 (alcance|replay sem alcance|anônimo|token)|^JWT real|^cliente fora alcance|^concorrência';
 }
 $selected=@(); if($casePatterns.ContainsKey([string]$r.regra)){$selected=@(@($all)+@($asserts)|Where-Object {$_.caso -match $casePatterns[[string]$r.regra]}|Sort-Object arquivo,indice -Unique)}
 $finding=[string]$r.achado;$gap=[string]$r.lacuna;$state='D26 parcial preservada; D27 complementa apenas casos ligados'
 $sql=@();$auditoria='Consultar auditoria GET por entidade da família, quando registrada na fonte; não inferir ausência/efeito para casos sem GET/SQL específico.'
 switch($r.regra){
 'RN14'{$state='ajuste E052 executado HTTP/SQL depois V10';$finding='D27 distingue divergencia, contagem e quarentena. Ajustes45/0/35 aplicados porSupervisor/replay; reserva ativa e revisao superada recusadas. Quarentena inicial e avaria preservam fisico/reserva, sem liberacao implicita. SELECT ajustes28/0+auditoria6/0 e variantes106/0.';$gap='Bloqueio schema E052 daD26 e historico, resolvido porV10DEV e fixJava; nao permanece ativo. Outros motivos operacionais sao limites dos casos, nao impedimento deste ajuste.';$sql=@('orchestracao/.runtime/d27-prumo-ajustes-final-20261007T014149078.json;28/0.','orchestracao/.runtime/d27-prumo-variantes-conferencia-20261007T021145197.json;106/0 sobre fotografia020903456, unidade23 quarentena inicial.')}
 'RN21'{$state='marcos armazenagem e financeiro naozero confrontados';$finding='Financeiro23/24 COMPLETO50 e fechamento14 APROVADOv2 em familia sem fatos, sem inventar historia fisica. Outra familia29/14: armazenagem inicia nos movimentosHTTP reais, anteriorFIFO nao inicia cobranca; unidade23 quarentena inicial sem inicio excluida. Previsoes26/28 pico4/3.75 e avaria proporcional comprovadas106/0.';$gap='D26 snapshot20 anulado/desatualizado permanece preservado, sem impedir naozero50D27. Previsoes26/28 de ciclo futuro nao sao aprovacao; historia anterior a transformacao continua PENDENTE deliberada.';$sql=@('orchestracao/.runtime/d27-prumo-casos-20261007T012544553.json;65/0 familia21/10.','orchestracao/.runtime/d27-prumo-variantes-conferencia-20261007T021145197.json;106/0 familia29/14.')}
 'AC07'{$state='fechamento naozero50 aprovado e replay/versoes comprovados';$finding='CorteUTC06->07 encerrado, calculos23/24 minimo complementar50, fechamento14APROVADOv2; v1SUPERADA conservada e replay/versao velha recusada. Futuro15EM_REVISAO nao aprova antes corte. SELECT65/0 confirma estados/versoes/snapshots.';$gap='PropostaAC nao homologada. D26 fato3 ANULADO/calculo20 desatualizado e historico separado; nao e bloqueio atual da aprovacao50. Todas sobreposicoes/correcoes/meses nao certificadas por esse caso.';$sql=@('orchestracao/.runtime/d27-prumo-casos-20261007T012544553.json;calculos22/23/24, fechamento14versoes1/2 e15futuro.')}
 'RN24'{$state='automacao concorrente green HTTP+SQL ao vivo; historico offline preservado';$finding='D279E93BDC2/JAR4304: par200/409, GETs/replay, pedido26 reservado80 e25RASCUNHO0, fisico100/reservado80/bloqueado20/disponivel0. Doze amostrasSQL originais mostram requests73->72->gate84, mesmo recurso KEY e PID48356. Predicado de fila corrigido porPrumo, fixtures9/0, reconciliacao12/0 sem novoSQL e Vigia favoravel. SELECT final24/0 confirma saldo/operacoes/snapshots/auditorias. OnlineWitness=false/falha original preservados. Reservas30/31 e reversao30 serial106/0 sao recorte distinto.';$gap='D2748A39681/JAR4304 concluiu a automacao green unica em fonteCAC92281/familia27/pedidos28/29: OnlineWitness=true, amostraSQL simultanea reader87/gate88/PID19664; par200/409 e GET/replay/saldo100/80/20/0. Prova anterior12amostras/flagfalse permanece historica. SELECT green24/0 confirma efeitos/saldo/UUIDs na familia27; snapshot e auditoria integrais separados dos checks de estado/versao. Pedidos25/26 concluidos nao sao reutilizaveis para nova reserva. 18456D26 nao e bloqueio atual. Nao certificar todos interleavings pelas doze amostras.';$sql=@('orchestracao/.runtime/d27-prumo-concorrencia-D2748A39681.json;WITNESS_SQL_COMPROVADO online, reader87/gate88/API19664, familia27/13/pedidos28/29.','d27-D2748A39681-http.json;16HTTP/2assertivas, phaseconcluido e GET/replay/saldo100/80/20/0.','orchestracao/.runtime/d27-prumo-concorrencia-final-select-20261007T024151964.json;24/0 green, fonteHTTP/hashEA853 e familia27/13/pedidos28/29, sem novaSQL de familia25.','orchestracao/.runtime/d27-prumo-gate-D279E93BDC2-reconciliacao.json;12/0 sobre fotografia original de02:19:05-08UTC, sem nova consulta.','orchestracao/.runtime/d27-prumo-concorrencia-D279E93BDC2.json;gate84/requests72,73/PID48356, hash original preservado.','orchestracao/.runtime/d27-prumo-concorrencia-final-select-20261007T023303815.json;24/0 saldo100/80/20/0 e efeitos unicos, nao disponivel20.','d27-concorrencia-fotografia-diagnostico.md;tempo/limites.','orchestracao/.runtime/d27-prumo-variantes-conferencia-20261007T021145197.json;pedidos30/31 serial106/0.')}
 'RN25'{$state='retirada D26 historica; ajustes novos D27 comprovados';$finding='Retirada/baixa pelas rotas D26 continuam prova historica sem nova alteracao nesse fluxo. Ajuste de contagem E05245/0/35 agora executado, preservandoorigens/historico/fatos/movimentos e saldo35/reservado0,28/0+6/0.';$gap='Nao reexecutada retirada D27 por ausencia de mudanca nesse fluxo; nao a certificar com ajuste. Transporte/TMS e fiscal real fora escopo. Schema E052 nao esta bloqueado atualmente.';$sql=@('orchestracao/.runtime/d27-prumo-ajustes-final-20261007T014149078.json;somente ajustes, nao retirada.','d26-regras.json;RN25 e recortes de retirada historicos exatos.')}
 'AC14'{$state='contrato contingencia D26 preservado; ajuste D27 validado';$finding='Contingencia/coletor segue provas HTTP D26 separadas; ajusteE052 deixou de estar bloqueado, aplicacoes/replay/rollback e SELECT28/0+6/0 validos.';$gap='Nao testados equipamento offline, interrupcao real de rede e recuperacao geral. Sao limites operacionais especificos; nao manter schemaE052 como impedimento atual.';$sql=@('orchestracao/.runtime/d27-prumo-ajustes-final-20261007T014149078.json;28/0 ajuste, nao certifica indisponibilidade/coletor.')}
 'RN08'{$state='variantes tecnicas HTTP executadas; SELECT106/0 confrontado';$finding='Tabela especifica7 vinculada explicitamente, padrao5 independente; codigo duplicado409TABELA_DUPLICADA, vinculo sobreposto409VIGENCIA_SOBREPOSTA e proprietario alheio409CONTEXTO_TABELA_INVALIDO. Lista final conserva um vinculo na7; replay e Operacao403. Tabelas de codigos distintos sao permitidas: tentativa200/expected409 preservada como erro do roteiro.';$gap='Familia29/armazem14; SELECT106/0 ligado a fotografia020903456 e reconciliacaoDTO021145197. Encerramentos historicos D26 separados, sem afirmar todas vigencias por estas variantes.';$sql=@('orchestracao/.runtime/d27-prumo-variantes-conferencia-20261007T021145197.json;106/0 fotografiaSQL020903456; servico10/tabelas6/7/8/vinculo e contrato7, GET atual D27AAEE9EB8; confrontado, sem nova leitura na reconciliacaoDTO.')}
 'RN15'{$state='mistura SKU recusada por HTTP com rollback GET';$finding='D27EF267FD7: unidade21 SKU15 e22 SKU16, mesma nota18/pedido19, ainda sem endereco. Reagrupamento409ORIGENS_INCOMPATIVEIS, GET de ambas fontes/quantidades/versoes igual antes/depois. Unidade isolada de cada SKU criada via HTTP.';$gap='SELECT106/0 familia29/14 confrontado; separa mistura SKU de recusa por lote/data ou transformacao apos enderecamento. Nao certifica todos tipos de embalagem.';$sql=@('orchestracao/.runtime/d27-prumo-variantes-conferencia-20261007T021145197.json;106/0 fotografiaSQL020903456; unidades21-25 e conteudos/origens da nota18/19, sem SQL DML.')}
 'RN17'{$state='quarentena/avaria/reserva e reversao explicita confrontadas HTTP';$finding='Quarentena inicial unidade23 excluida de FIFO/reserva, fisico60/disponivel40. Avaria5 em unidade21 reservada25 conserva reserva/fisico; revalidacao409RESERVA_IMPEDIDA e GETpodeProsseguir=false. Gestor reconhece responsabilidade sem liberar reserva. Supervisor reverte somente pelo comando explicito/replay, fisico60/reservado0/disponivel20; quarentena/avaria continuam.';$gap='SELECT106/0 pedido30 revertido/pedido31 reservado e avaria3 confrontado. Concorrencia simultanea exige witness proprio, nao inferido deste caso serial.';$sql=@('orchestracao/.runtime/d27-prumo-variantes-conferencia-20261007T021145197.json;106/0 fotografiaSQL020903456; pedido30/31, unidades21/23/25 e avaria3, GET final D27AAEE9EB8.')}
 'RN23'{$state='FIFO real por origens/lotes/datas e recusas confrontadas';$finding='D27EF267FD7: nota18 tem FIFO da primeira chegada, preservando chegadas reais distintas; nota19 FIFO mais recente. Sugestao/reservaA25 usa unidade21 antiga20 +25 recente5, exclui23 quarentena. ReservaC15 conserva lotesL1/L2 da nota18, quantidades10+5 e dataFIFO. Reagrupamentos por chegadas/lotes distintos409 preservam GET. Nenhum replayXML403 e atribuido ao FIFO.';$gap='SELECT106/0 origens/FIFO/linhas ativas e revertidas confrontado; desempates por nivel/codigo e bobina excepcional D26 sao provas historicas separadas.';$sql=@('orchestracao/.runtime/d27-prumo-variantes-conferencia-20261007T021145197.json;106/0 fotografiaSQL020903456; notas18/19, pedidos30/31 e unidades21-25; ligar somente esse recorte.')}
 'AC04'{$state='pico e ocupacao proporcional ficticios confrontados HTTP';$finding='Previsao26 para proximo diaUTC: pico4 x tarifa especifica7=28. Quarentena inicial sem inicio nao cobra; reserva nao reduz pico. Avaria reconhecida5/20 suspende0.25 da equivalencia, previsao28 pico3.75/subtotal26.25; fisico/origens continuam intactos. GET26 preserva snapshot54.';$gap='Previsao de ciclo ainda aberto, sem aprovar antes do corte. Esses picos/prorratas tecnicos foram executados; DST/mes/fusos/outros tipos continuam delimitados, AC04 permanece proposta comercial.';$sql=@('orchestracao/.runtime/d27-prumo-variantes-conferencia-20261007T021145197.json;106/0 fotografiaSQL020903456; memorias26/28, unidade21, avaria3 e inicio dos enderecamentos; SELECT106/0 confrontado.')}
 'AC08'{$state='avaria/responsabilidade e efeito financeiro confrontados HTTP';$finding='Avaria3 parcial5/base20/equivalencia1. Calculo27PENDENTE por RESPONSABILIDADE_AVARIA_PENDENTE/totalNULL. Supervisor403 e Gestor200RODOGARCIA/replay; suspensao0.25 desde ocorrencia. Calculo28COMPLETO53.75, pico3.75, baseGRIS750; snapshot anterior26=54 e hash distinto, GET/replay finais. Nao usa previsao sem avaria como prova.';$gap='SELECT106/0 quantidade/base/equivalencia, responsabilidades/fatos/auditoria e memorias26/27/28 confrontado. PropostaAC nao homologada; outras responsabilidades e reparo D26 separados, sem certificar todas combinacoes.';$sql=@('orchestracao/.runtime/d27-prumo-variantes-conferencia-20261007T021145197.json;106/0 fotografiaSQL020903456; avaria3/unidade21/contrato7/calculos26/27/28, fontesGET D27AAEE9EB8.')}
 'RN22'{$state='criacao XML e limites numericos corrigidos e confrontados HTTP/SQL';$finding='E161: tres perfis criam XML ficticio seguro, origem/nota/SKU/unidade/integralidade/replay/duplicidade/auth/XXE. D2755FEBD14/JAR4304: cinco numericos extremos recusam400 antes normalizacao/agregacao; positivo2E0+3E0=5 pedido32/replay/GET. SELECT20/0 confirma ausencia das cinco recusas, snapshot/origem/auditorias unicas do32 e saldo35/reservado0. Reds500 dos JAR418/C05B permanecem historicos, corrigidos por long e ordem da guarda. XML nao reserva/retira/emite.';$gap='Assinatura/autorizacao fiscal, todos layouts/XML de terceiros e operacao real nao homologados; interpretacao minima de layout identificada no contrato. Casos normais iniciais foram executados noJAR417/418, nao reclassificar todos como execucao4304.';$sql=@('orchestracao/.runtime/d27-prumo-casos-20261007T012544553.json;65/0 RN22 pedidos19/20/21 cliente19/armazem9.','orchestracao/.runtime/d27-prumo-xml-final-20261007T022226255.json;20/0 fonteHTTP D2755FEBD14, cinco recusas e positivo32 proprio, sem reserva.','orchestracao/.runtime/d27-prumo-xml-ausencias-20261007T021546056.json;seis operacoes historicas sem efeitos, nao aprova seus HTTP500.')}
 'AC13'{$state='schema V10 e ajuste HTTP corrigidos; proposta não homologada';$finding='V10 DEV aplicada por Prumo. Ajustes50→45,50→0 e45→35 via Supervisor; replay/perfis/alcance/delta inválido/reserva ativa/revisão superada e GET físico35/reservado0. Zero mantém localização histórica, desassocia ocupação e inativa; sem DELETE.';$gap='SELECT final28/0 e auditoria6/0 conferidos; primeiro409/localização e rollback preservados. Não aceita todos motivos/variedades de contagem por2xx.';$sql=@('orchestracao/.runtime/d27-prumo-ajuste-zero-D2763484C74.json; rollback inicial específico.','orchestracao/.runtime/d27-prumo-ajustes-final-20261007T014149078.json;28/0 contagens3/4/5, unidades15/16, pedido23/calculo25; auditoria especifica6/0 em d27-prumo-ajustes-auditoria.json.')}
 'RN20'{$finding='Páginas com IDs, total/ordem, fim vazio, limites100/101/overflow/negativa e alcance; estoque35 com filtros e unidade16 inativa/histórico preservado.';$gap='Conferidos filtros publicados; nem toda combinação de filtros/ordenação ou volume real está homologada.';$sql=@('orchestracao/.runtime/d27-prumo-casos-20261007T012544553.json; somente produtos10/11/12 e endereços28/29/30 cliente23/armazém11.')}
 'RN28'{$finding+=' D27 acrescenta assertivas de conteúdo/metadados/ordem/isolamento em páginas de produtos/endereços/estoque/pedidos XML/contagens/cálculos/históricos.';$gap='Demais combinações não exaustivas, exportações/frontend/relatórios operacionais reais fora do ensaio.'}
 'RN27'{$finding='Novo financeiro fictício mínimo complementar50, cicloUTC06→07 encerrado, cálculos23/24COMPLETO, memória subtotal0+50+GRIS0 e fechamento14APROVADO v1/v2; replay e versões preservadas. Previsão22/fechamento15 não aprova antes do corte.';$gap='Mínimo fictício não homologa preço, mês, diária, fuso/DST/prorrata/todas basesGRIS. Fonte física nova atual está no ciclo aberto; fatoADICIONAL não pode preceder criação do pedido. CALCULO_DESATUALIZADO realD26 e regressão isolada separados, sem forçar20 anulado.';$sql=@('orchestracao/.runtime/d27-prumo-casos-20261007T012544553.json; financeiro cálculos22/23/24 e versões1/2 de14, futuro15, todos IDs explícitos.')}
 'AC06'{$finding='MinimoINTEGRAL50/subtotal0/GRISNA0 no corteUTC encerrado, aprovacao50/GET/replay/SQL65_0. Familia29/14 nova: minimo100 PROPORCIONAL_DIAS1/2=50, tabela especifica7, subtotal28/complemento22, GRIS1% base800 POR_CICLO1/2=4,total54. Avaria5/20 reconhecida:subtotal26.25/complemento23.75/base750/GRIS3.75,total53.75 com memoria/GET/replay.';$gap='Estas modalidades tecnicas foram executadas; outras bases/meses/fusos delimitados. Valores ficticios, AC06 nao homologada; previsao nao aprova ciclo futuro.';$sql=@('orchestracao/.runtime/d27-prumo-casos-20261007T012544553.json; contrato6/tabela5/servico8/calcs23/24/fechamento14.','orchestracao/.runtime/d27-prumo-variantes-conferencia-20261007T021145197.json;106/0 fotografiaSQL020903456; contrato7/tabela7/servico10/calcs26/27/28; SELECT106/0 confrontado.')}
 'AC11'{$finding+=' D27 exige JWT/HTTPS real, três perfis RN22, alcance/replay negados, flags no caminho serial/concorrente capturadas; witness só real por rodada.';$gap='Todas combinações não exaustivas. Pares ou fixtures offline não substituem witness SQL; atestado válido não certifica autorização de toda rota.'}
 }
 $rules+=@([ordered]@{regra=[string]$r.regra;requisito=[string]$r.requisito;fonte=[string]$r.fonte;estado=$state;achadoD27=$finding;limite=$gap;fonteHistorica='d26-regras.json; localizar '+[string]$r.regra;endpoints=@($endpoints|ForEach-Object {$_.id});casosD27=$selected;GETsD27=@($selected|Where-Object {$_.metodo -eq 'GET' -and $_.estado -eq 'aprovado'});SQLRecortes=$sql;SQLCertificaTodasRotas=$false;auditoria=$auditoria;ACProposta=([string]$r.regra -match '^AC')})
}
Write-Json 'd27-regras.json' ([ordered]@{utc=[DateTime]::UtcNow.ToString('o');regras=$rules.Count;backendTotalAprovado=$false;ACPropostasNaoHomologadas=$true;matriz=$rules})
$md=@('# D27 — requisito, casos, SQL e limites','', 'As 46 regras mantêm IDs/fontes D26. D27 fecha lacunas técnicas por casos novos; não homologa propostas AC ou toda operação. Expected/actual/perfil/endpoint/GET estão no JSON por caso; SQL refere somente a família/IDs descritos. Nenhum SELECT genérico certifica cada API.','', '[JSON por regra/caso/GET](d27-regras.json) | [Matriz endpoint](d27-matriz.md)','', '| Regra / fonte | Achado confrontado | SQL exato | Limite / não executado |','|---|---|---|---|')
foreach($r in $rules){$refs=@($r.casosD27|Sort-Object @{Expression={if($_.estado -eq 'aprovado'){0}else{1}}},arquivo,indice|Select-Object -First 3|ForEach-Object {'['+(Cell $_.caso)+']('+ $_.arquivo+') #'+$_.indice+' '+[string]$_.expected+'→'+[string]$_.actual});$sqlRefs=@($r.SQLRecortes|ForEach-Object {Sql-Link $_});$md+=('|'+$r.regra+' ['+(Cell $r.requisito)+']('+$r.fonte+')|'+(Cell $r.achadoD27)+' '+($refs -join '; ')+'|'+($sqlRefs -join '; ')+'|'+(Cell $r.limite)+'|')}
Write-Md 'd27-regras.md' $md
Write-Json 'd27-contagens.json' $counts
$request=@()
foreach($f in @(Get-ChildItem (Join-Path $backend 'evidencias/d27-D27*-http.json')|Sort-Object Name)){$j=Read-Json $f.FullName;if($j.fase -like 'offline*'){continue};$request+=@([ordered]@{rodada=[string]$j.rodada;fase=[string]$j.fase;fonteHTTP='backend/evidencias/'+$f.Name;retomadaDe=[string]$j.ids.retomadaDe;clienteId=$j.ids.clienteId;armazemId=$j.ids.armazemId;produtoId=$j.ids.produtoId;pedidoEntradaId=$j.ids.pedidoEntradaId;notaId=$j.ids.notaId;pedidosXml=$j.ids.pedidosXml;contagens=$j.ids.contagens;pedidoReservaContagemId=$j.ids.pedidoReservaContagemId;calculoAjusteId=$j.ids.calculoAjusteId;calculoFinanceiroId=$j.ids.calculoFinanceiroId;previsaoFinanceiraId=$j.ids.previsaoFinanceiraId;recalculoFinanceiroId=$j.ids.recalculoFinanceiroId;fechamentoFinanceiroId=$j.ids.fechamentoFinanceiroId;fechamentoPrevisaoId=$j.ids.fechamentoPrevisaoId;financeiroVersaoAtual=$j.ids.financeiroVersaoAtual;produtosLista=$j.ids.produtosLista;concorrenciaPedidos=$j.ids.concorrenciaPedidos;servicoLimiteTemporalId=$j.ids.servicoLimiteTemporalId})}
Write-Json 'd27-persistencia-casos.json' ([ordered]@{utc=[DateTime]::UtcNow.ToString('o');demanda='D27';estado='FONTES_HTTP_ATUAIS_PARA_SELECT_FOCAL_SEM_DML';rodadas=$request;instrucao='Cada fonte é instante próprio; retomadas finalizam estado atual. Não comparar snapshot inicial com versão atual sem ligação. Preservar tentativaSQL61/9; comparar último GET/versão2 explicitamente. Nenhum INSERT/DELETE/reset ou prova genérica por endpoint.'})
$counts|ConvertTo-Json -Compress
