const verbs: Record<string, string> = {
    listar: "Consultar lista",
    consultar: "Consultar detalhe",
    criar: "Novo registro",
    alterar: "Corrigir descrição",
    encerrar: "Solicitar encerramento",
    reativar: "Reativar cadastro",
    configurar: "Configurar",
    nota: "Registrar nota manual",
    xml: "Importar XML existente",
    iniciar: "Iniciar conferência",
    chegada: "Registrar chegada física",
    chegadas: "Consultar chegadas",
    efetivar: "Efetivar carga integral",
    estornar: "Estornar chegada",
    cancelar: "Registrar cancelamento",
    entradas: "Consultar entradas conferidas",
    unitizar: "Distribuir em unidades",
    progresso: "Consultar progresso",
    dividir: "Dividir unidade",
    reagrupar: "Reagrupar unidades",
    lerCodigo: "Ler UUID da unidade",
    etiqueta: "Consultar / reimprimir etiqueta",
    saldo: "Consultar saldo do SKU",
    historico: "Consultar movimentos",
    bloquear: "Bloquear preventivamente",
    liberar: "Confirmar liberação",
    avariar: "Registrar bloqueio por avaria",
    registrar: "Registrar fato",
    reconhecer: "Reconhecer responsabilidade",
    reparar: "Registrar reparo",
    importarXml: "Criar pedido por XML",
    sugerir: "Consultar sugestão FIFO",
    justificar: "Justificar exceção FIFO",
    reservar: "Confirmar reserva integral",
    revalidar: "Revalidar disponibilidade",
    reverter: "Reverter reserva",
    ler: "Conferir leitura da reserva",
    separar: "Confirmar separação",
    documento: "Registrar documento existente",
    retirar: "Confirmar retirada física",
    fatos: "Consultar fatos físicos",
    retornar: "Retornar às posições",
    devolver: "Registrar devolução / nova entrada",
    servicos: "Consultar serviços",
    criarServico: "Cadastrar serviço",
    tabelas: "Consultar tabelas",
    tabela: "Consultar tabela",
    criarTabela: "Criar tabela e itens",
    encerrarTabela: "Encerrar vigência da tabela",
    vinculos: "Consultar vínculos",
    vincular: "Vincular tabela ao cliente",
    encerrarVinculo: "Encerrar vínculo",
    contratos: "Consultar contratos",
    encerrarContrato: "Encerrar contrato",
    sugestoes: "Consultar sugestões de serviço",
    anular: "Anular fato identificado",
    marcos: "Consultar marcos financeiros",
    marco: "Registrar marco financeiro",
    calcular: "Solicitar cálculo ao servidor",
    versoes: "Consultar versões",
    versao: "Consultar versão e hash",
    demonstrativo: "Baixar demonstrativo guardado",
    tratativas: "Consultar tratativas",
    tratar: "Registrar tratativa externa",
    preparar: "Preparar",
    aprovar: "Aprovar ciclo integral",
    rejeitar: "Rejeitar ciclo integral",
    reabrir: "Reabrir ciclo",
    entregar: "Registrar entrega manual",
    confirmarNaoEmissao: "Registrar declaração de não emissão",
    registrarNfse: "Registrar referência NFS-e",
    resolverSaldo: "Resolver saldo financeiro",
    ajustar: "Registrar ajuste",
    contar: "Registrar contagem física",
    revisoes: "Consultar revisões",
    aplicar: "Aplicar ajuste conferido",
    revisar: "Revisar dados levantados",
    confirmar: "Confirmar",
    resolverCancelamento: "Resolver cancelamento pendente",
    conciliar: "Conciliar fato manualmente",
    previa: "Conferir prévia Excel",
    cliente: "Consultar fiscal do cliente",
    armazem: "Consultar fiscal do armazém",
    complementarCliente: "Complementar fiscal do cliente",
    complementarArmazem: "Complementar fiscal do armazém",
    referencias: "Consultar referências fiscais do SKU",
    referenciar: "Registrar referência fiscal",
    solicitar: "Solicitar encerramento definitivo",
    inativar: "Confirmar inativação",
    remanescente: "Resolver estoque remanescente",
    vigencia: "Encerrar vigência identificada",
};
export const actionLabel = (id: string) =>
    verbs[id.split(".")[1]] ?? id.split(".")[1];
